'use client'

import { useEffect, useMemo, useState } from 'react'

type Payment={reference:string;amount:number;currency:string;status:string;transaction_id:number|null;refunded_amount:number;refund_reference:string|null;refund_status:string|null;paid_at:string|null}
type Order={id:string;order_number:string;customer_name:string;email:string;phone:string;total:number;currency:string;status:string;payment_status:string;paystack_reference:string|null;created_at:string;payment:Payment|null}

const money=(n:number,currency='NGN')=>currency==='NGN'?`₦${Number(n).toLocaleString('en-NG',{maximumFractionDigits:2})}`:`${currency} ${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`
const badge=(value:string)=>`order-status order-status-${value.replace(/[^a-z-]/g,'-')}`

export function OrderPaymentsManager(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Order|null>(null),[refundAmount,setRefundAmount]=useState(''),[refundBusy,setRefundBusy]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/orders',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load orders.');setOrders(d.orders??[])}catch(e){setError(e instanceof Error?e.message:'Could not load orders.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>orders.filter(o=>{const q=query.trim().toLowerCase();const matches=!q||[o.order_number,o.customer_name,o.email,o.paystack_reference??'',o.payment?.reference??''].some(v=>v.toLowerCase().includes(q));return matches&&(status==='all'||o.payment_status===status)}),[orders,query,status])
 const refund=async()=>{if(!selected||refundBusy)return;setRefundBusy(true);setMessage('');setError('');try{const r=await fetch('/api/admin/payments/refund',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:selected.id,amount:refundAmount||undefined})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Refund could not be initiated.');setMessage(`Refund initiated: ${money(Number(d.amount),selected.currency)} · ${d.status}`);setSelected(null);setRefundAmount('');await load()}catch(e){setError(e instanceof Error?e.message:'Refund could not be initiated.')}finally{setRefundBusy(false)}}
 return <section className="payment-ops">
  <div className="payment-ops-head"><div><p className="payment-kicker">Commerce / payments</p><h1>Orders & payments</h1><p>Monitor payment state, reconcile successful transactions and initiate refunds without exposing Paystack credentials.</p></div><button className="payment-refresh" onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div>
  <div className="payment-metrics"><div><span>Orders</span><strong>{orders.length}</strong></div><div><span>Paid</span><strong>{orders.filter(o=>o.payment_status==='paid').length}</strong></div><div><span>Pending</span><strong>{orders.filter(o=>o.payment_status==='pending').length}</strong></div><div><span>Needs review</span><strong>{orders.filter(o=>['failed','unpaid'].includes(o.payment_status)).length}</strong></div></div>
  <div className="payment-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, customer or reference"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All payment states</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="unpaid">Unpaid</option><option value="refunded">Refunded</option></select></div>
  {error&&<div className="payment-alert payment-alert-error" role="alert">{error}</div>}{message&&<div className="payment-alert payment-alert-success" role="status">{message}</div>}
  {loading?<div className="payment-empty">Loading payment records…</div>:filtered.length===0?<div className="payment-empty"><strong>No matching orders</strong><span>Try another search or payment filter.</span></div>:<div className="payment-table-wrap"><table className="payment-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Transaction</th><th></th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><strong>{o.order_number}</strong><small>{new Date(o.created_at).toLocaleString()}</small></td><td><strong>{o.customer_name}</strong><small>{o.email}</small></td><td>{money(o.total,o.currency)}</td><td><span className={badge(o.payment_status)}>{o.payment_status}</span>{o.payment?.refund_status&&<small>Refund: {o.payment.refund_status}</small>}</td><td><small>{o.payment?.reference||'—'}</small>{o.payment?.transaction_id&&<small>TX {o.payment.transaction_id}</small>}</td><td>{o.payment_status==='paid'&&<button className="payment-action" onClick={()=>setSelected(o)}>Refund</button>}</td></tr>)}</tbody></table></div>}
  {selected&&<div className="refund-overlay" role="dialog" aria-modal="true" aria-labelledby="refund-title"><div className="refund-dialog"><button className="refund-close" onClick={()=>setSelected(null)} aria-label="Close">×</button><p className="payment-kicker">Refund payment</p><h2 id="refund-title">{selected.order_number}</h2><p className="refund-copy">Paid {money(selected.payment?.amount??selected.total,selected.currency)}. Leave the amount blank for a full remaining refund.</p><label>Refund amount (NGN)<input type="number" min="0.01" step="0.01" value={refundAmount} onChange={e=>setRefundAmount(e.target.value)} placeholder={money(Math.max(0,Number(selected.payment?.amount??selected.total)-Number(selected.payment?.refunded_amount||0)))}/></label><div className="refund-actions"><button onClick={()=>setSelected(null)} disabled={refundBusy}>Cancel</button><button className="payment-primary" onClick={()=>void refund()} disabled={refundBusy}>{refundBusy?'Initiating…':'Initiate refund'}</button></div></div></div>}
 </section>
}
