'use client'
import { useEffect, useState } from 'react'
type Item={id:string;name:string;slug:string;status:string}
export default function CampaignTargets({campaignId,onSaved}:{campaignId:string;onSaved?:()=>void}){
 const [products,setProducts]=useState<Item[]>([]),[collections,setCollections]=useState<Item[]>([]),[selectedP,setSelectedP]=useState<string[]>([]),[selectedC,setSelectedC]=useState<string[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!open)return;Promise.all([fetch('/api/admin/products?limit=100'),fetch('/api/admin/collections')]).then(async([p,c])=>{const pj=await p.json(),cj=await c.json();if(!p.ok)throw new Error(pj.error||'Could not load products');if(!c.ok)throw new Error(cj.error||'Could not load collections');setProducts((pj.products||[]).filter((x:Item)=>x.status==='published'));setCollections((cj.collections||[]).filter((x:Item)=>x.status==='published'))}).catch(e=>setError(e.message));fetch(`/api/admin/campaigns/${campaignId}/targets`).then(r=>r.json()).then(j=>{setSelectedP((j.products||[]).map((x:{product_id:string})=>x.product_id));setSelectedC((j.collections||[]).map((x:{collection_id:string})=>x.collection_id))}).catch(()=>{})},[open,campaignId])
 const save=async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/admin/campaigns/${campaignId}/targets`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({product_ids:selectedP,collection_ids:selectedC})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save targets');setOpen(false);onSaved?.()}catch(e){setError(e instanceof Error?e.message:'Could not save targets')}finally{setBusy(false)}}
 return <div className="mt-4"><button type="button" onClick={()=>setOpen(v=>!v)} className="text-xs uppercase tracking-[.12em] underline underline-offset-4">{open?'Close targets':'Products & collections'}</button>{open&&<div className="mt-4 rounded-xl border border-black/10 bg-[#F7F3EC] p-4"><p className="text-[10px] uppercase tracking-[.14em] text-black/45">Campaign targets</p><div className="mt-3 grid gap-4 md:grid-cols-2"><div><p className="text-xs font-medium">Products</p><div className="mt-2 max-h-48 space-y-2 overflow-auto">{products.map(p=><label key={p.id} className="flex gap-2 text-sm"><input type="checkbox" checked={selectedP.includes(p.id)} onChange={e=>setSelectedP(v=>e.target.checked?[...v,p.id]:v.filter(x=>x!==p.id))}/>{p.name}</label>)}</div></div><div><p className="text-xs font-medium">Collections</p><div className="mt-2 max-h-48 space-y-2 overflow-auto">{collections.map(c=><label key={c.id} className="flex gap-2 text-sm"><input type="checkbox" checked={selectedC.includes(c.id)} onChange={e=>setSelectedC(v=>e.target.checked?[...v,c.id]:v.filter(x=>x!==c.id))}/>{c.name}</label>)}</div></div></div><button type="button" disabled={busy} onClick={save} className="mt-4 bg-[#111] px-4 py-2 text-xs uppercase tracking-[.12em] text-white">{busy?'Saving…':'Save targets'}</button>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</div>}</div>
}
