import { NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'
const clean=(v:unknown,max:number)=>typeof v==='string'?v.trim().slice(0,max):''
const validSlug=(v:string)=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v)
const validUuid=(v:unknown)=>v===null||typeof v==='undefined'||(typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))
const statuses=new Set(['draft','published','archived']);const jsonError=(message:string,status:number)=>NextResponse.json({error:message},{status})
type ProductPayload={name:string;slug:string;short_description:string;description:string;base_price:number;currency:'NGN';status:string;is_featured:boolean;badge:string|null;seo_title:string|null;seo_description:string|null;seo_keywords:string[];category_id:string|null;material:string|null;dimensions:string|null;capacity:string|null;care_instructions:string|null;delivery_returns:string|null;features:string[]}
type ParsedPayload={data:ProductPayload}|{error:string}
function payload(body:Record<string,unknown>):ParsedPayload{const name=clean(body.name,160),slug=clean(body.slug,120),short_description=clean(body.short_description,500),description=clean(body.description,10000),price=typeof body.base_price==='number'?body.base_price:Number(body.base_price),category_id=body.category_id===''?null:body.category_id??null;if(name.length<2||!validSlug(slug)||!Number.isFinite(price)||price<0||price>1000000000||!validUuid(category_id))return{error:'Please check the product name, slug, category and NGN price.'};const status=typeof body.status==='string'&&statuses.has(body.status)?body.status:'draft';const keywords=Array.isArray(body.seo_keywords)?body.seo_keywords.filter((x):x is string=>typeof x==='string').map(x=>x.trim().slice(0,80)).filter(Boolean).slice(0,20):[];const features=Array.isArray(body.features)?body.features.filter((x):x is string=>typeof x==='string').map(x=>x.trim().slice(0,160)).filter(Boolean).slice(0,30):[];return{data:{name,slug,short_description,description,base_price:price,currency:'NGN',status,is_featured:body.is_featured===true,badge:clean(body.badge,40)||null,seo_title:clean(body.seo_title,70)||null,seo_description:clean(body.seo_description,170)||null,seo_keywords:keywords,category_id:category_id as string|null,material:clean(body.material,200)||null,dimensions:clean(body.dimensions,200)||null,capacity:clean(body.capacity,500)||null,care_instructions:clean(body.care_instructions,2000)||null,delivery_returns:clean(body.delivery_returns,1000)||null,features}}
export async function GET(request:Request){try{await requireRole(['catalog_admin']);const url=new URL(request.url);const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||100),1),100);const s=await createClient();const{data,error}=await s.from('products').select('id,name,slug,status,base_price,currency,is_featured,category_id').order('name').limit(limit);if(error)return jsonError('Could not load products.',500);return NextResponse.json({products:data??[]})}catch{return jsonError('Unable to load products.',500)}}
export async function POST(request:Request){try{const{user}=await requireRole(['catalog_admin']);if(!request.headers.get('content-type')?.toLowerCase().includes('application/json'))return jsonError('JSON request required.',415);let body:unknown;try{body=await request.json()}catch{return jsonError('Invalid JSON request.',400)}if(!body||typeof body!=='object'||Array.isArray(body))return jsonError('Invalid request.',400);const parsed=payload(body as Record<string,unknown>);if('error'in parsed)return jsonError(parsed.error,400);const s=await createClient();if(parsed.data.category_id){const{data:cat}=await s.from('categories').select('id').eq('id',parsed.data.category_id).eq('is_active',true).maybeSingle();if(!cat)return jsonError('Selected category is not available.',400)}const{data,error}=await s.from('products').insert({...parsed.data,created_by:user.id,updated_by:user.id}).select('id').single();if(error)return jsonError(error.code==='23505'?'A product with this slug already exists.':'Could not create product.',error.code==='23505'?409:400);return NextResponse.json({id:data.id},{status:201})}catch{return jsonError('Unable to create product.',500)}}
