import { NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'
const clean=(v:unknown,max:number)=>typeof v==='string'?v.trim().slice(0,max):''
const validSlug=(v:string)=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v)
const statuses=new Set(['draft','published','archived'])
const jsonError=(message:string,status:number)=>NextResponse.json({error:message},{status})
type ParsedPayload=|{error:string;data?:never}|{data:{name:string;slug:string;short_description:string;description:string;base_price:number;currency:'NGN';status:string;is_featured:boolean;badge:string|null;seo_title:string|null;seo_description:string|null;seo_keywords:string[]};error?:never}
function payload(body:Record<string,unknown>):ParsedPayload{const name=clean(body.name,160),slug=clean(body.slug,120),short_description=clean(body.short_description,500),description=clean(body.description,10000);const price=typeof body.base_price==='number'?body.base_price:Number(body.base_price);if(name.length<2||name.length>160||!validSlug(slug)||!Number.isFinite(price)||price<0||price>1000000000)return{error:'Please check the product name, slug and NGN price.'};const status=typeof body.status==='string'&&statuses.has(body.status)?body.status:'draft';const keywords=Array.isArray(body.seo_keywords)?body.seo_keywords.filter((x):x is string=>typeof x==='string').map(x=>x.trim().slice(0,80)).filter(Boolean).slice(0,20):[];return{data:{name,slug,short_description,description,base_price:price,currency:'NGN',status,is_featured:body.is_featured===true,badge:clean(body.badge,40)||null,seo_title:clean(body.seo_title,70)||null,seo_description:clean(body.seo_description,170)||null,seo_keywords:keywords}}}
export async function GET(request:Request){try{await requireRole(['catalog_admin','marketing_admin','content_admin','super_admin']);const url=new URL(request.url);const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||100),1),100);const supabase=await createClient();const{data,error}=await supabase.from('products').select('id,name,slug,status,base_price,currency,is_featured').order('name').limit(limit);if(error)return jsonError('Could not load products.',500);return NextResponse.json({products:data??[]})}catch{return jsonError('Unable to load products.',500)}}
export async function POST(request:Request){try{const{user}=await requireRole(['catalog_admin']);const userId=user.id;if(!request.headers.get('content-type')?.toLowerCase().includes('application/json'))return jsonError('JSON request required.',415);let body:unknown;try{body=await request.json()}catch{return jsonError('Invalid JSON request.',400)};if(!body||typeof body!=='object'||Array.isArray(body))return jsonError('Invalid request.',400);const parsed=payload(body as Record<string,unknown>);if(!('data'in parsed))return jsonError(parsed.error,400);const supabase=await createClient();const{data,error}=await supabase.from('products').insert({...parsed.data,created_by:userId,updated_by:userId}).select('id').single();if(error){const status=error.code==='23505'?409:400;return jsonError(error.code==='23505'?'A product with this slug already exists.':'Could not create product.',status)}return NextResponse.json({id:data.id},{status:201})}catch{return jsonError('Unable to create product.',500)}}
