import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { requireStaff } from "@/lib/auth/authorization";

const modules = [
  ["Orders", "Purchases, payment state, fulfilment and returns.", "/admin/orders"], ["Products", "Catalogue, pricing, variants and product media.", "/admin/products"], ["Collections", "Curate the edits customers discover first.", "/admin/collections"], ["Inventory", "Stock levels and controlled adjustments.", "/admin/inventory"], ["Customers", "Customer accounts and support context.", "/admin/customers"], ["Waitlist", "Follow up with customers watching pieces.", "/admin/waitlist"], ["Enquiries", "Website contact and custom bag requests.", "/admin/enquiries"], ["Campaigns", "Promotions, flash sales and announcement bars.", "/admin/campaigns"], ["Merchandising", "Control featured and promoted placement.", "/admin/merchandising"], ["Landing page", "Manage approved brand storytelling sections.", "/admin/content"], ["Journal", "Publish Zorah news and editorial stories.", "/admin/journal"], ["Scheduling", "Monitor scheduled publishing and expiry jobs.", "/admin/scheduling"], ["Team & roles", "Assign least-privilege administrator access.", "/admin/team"], ["Audit trail", "Review privileged administrative activity.", "/admin/audit"],
] as const;

export default async function AdminPage() {
  const { role } = await requireStaff();
  const supabase = await createClient();
  const [profiles, products, collections, campaigns, waitlist, enquiries, customOrders, allProfiles, allProducts] = await Promise.all([
    supabase.from("profiles").select("id", { count: "exact", head: true }), supabase.from("products").select("id", { count: "exact", head: true }), supabase.from("collections").select("id", { count: "exact", head: true }), supabase.from("campaigns").select("id", { count: "exact", head: true }), supabase.from("product_waitlists").select("id", { count: "exact", head: true }).eq("status", "waiting"), supabase.from("contact_requests").select("id", { count: "exact", head: true }).in("status", ["new", "in_progress"]), supabase.from("custom_order_requests").select("id", { count: "exact", head: true }).in("status", ["new", "reviewing", "quoted"]), supabase.from("profiles").select("role, is_active"), supabase.from("products").select("status"),
  ]);
  const roleCounts = (allProfiles.data ?? []).reduce<Record<string,number>>((a,p)=>{a[p.role]=(a[p.role]??0)+1;return a},{}); const productCounts=(allProducts.data??[]).reduce<Record<string,number>>((a,p)=>{const s=String(p.status);a[s]=(a[s]??0)+1;return a},{}); const totalUsers=profiles.count??0; const staffCount=(allProfiles.data??[]).filter(p=>p.role!=='customer').length; const customerCount=(allProfiles.data??[]).filter(p=>p.role==='customer').length; const published=productCounts.published??0; const totalProducts=allProducts.data?.length??0; const publishRate=totalProducts?Math.round(published/totalProducts*100):0; const staffRate=totalUsers?Math.round(staffCount/totalUsers*100):0;
  const visible=role==='super_admin'?modules:modules.filter(([, , href])=>{if(role==='catalog_admin')return ['/admin/products','/admin/collections','/admin/inventory'].includes(href);if(role==='order_admin')return href==='/admin/orders';if(role==='content_admin')return ['/admin/content','/admin/journal'].includes(href);if(role==='marketing_admin')return ['/admin/campaigns','/admin/merchandising'].includes(href);if(role==='support_admin')return ['/admin/customers','/admin/waitlist','/admin/enquiries'].includes(href);if(role==='operations_admin')return ['/admin/scheduling'].includes(href);return false});
  return <main><header><div><div><Link href="/admin" className="font-serif text-2xl tracking-[.12em]">ZORAH</Link><p className="mt-1 text-[10px] uppercase tracking-[.25em]">Commerce studio</p></div><div className="flex gap-5"><Link href="/" className="text-xs uppercase tracking-[.18em] text-black/55">Brand site ↗</Link><Link href="/shop" className="text-xs uppercase tracking-[.18em]">Storefront ↗</Link></div></div></header><section><div className="zorah-dashboard-hero"><div><p className="zorah-dashboard-kicker">Admin / overview</p><h1 className="mt-3 text-5xl sm:text-6xl">Good to see you.</h1><p className="zorah-dashboard-sub mt-4">The operating centre for Zorah. Each staff member sees the workspace their role permits; the Super Admin sees everything.</p></div><div className="zorah-dashboard-actions"><Link href="/admin/products/new" className="zorah-dashboard-primary">Add product</Link>{role==='super_admin'&&<Link href="/admin/team" className="zorah-dashboard-secondary">Manage team</Link>}</div></div>
  <div className="zorah-dashboard-stats"><div className="zorah-dashboard-stat"><span>Users</span><strong>{totalUsers}</strong><em>{customerCount} customers · {staffCount} staff</em></div><div className="zorah-dashboard-stat"><span>Products</span><strong>{products.count??0}</strong><em>{published} published</em></div><div className="zorah-dashboard-stat"><span>Orders</span><strong>0</strong><em>order table not connected yet</em></div><div className="zorah-dashboard-stat"><span>Revenue</span><strong>₦0</strong><em>verified order revenue only</em></div></div>
  <div className="zorah-dashboard-analytics"><section className="zorah-dashboard-panel"><div className="zorah-dashboard-panel-head"><div><span>Business pulse</span><h2 className="mt-2 text-2xl">Catalogue health</h2></div></div><div className="zorah-chart-row"><div className="zorah-donut" style={{background:`conic-gradient(#173d32 0 ${publishRate}%,#e7e0d5 ${publishRate}% 100%)`}}><div><strong>{publishRate}%</strong><span>published</span></div></div><div className="zorah-chart-copy"><div><strong>{collections.count??0}</strong><span>collections</span></div><div><strong>{campaigns.count??0}</strong><span>campaigns</span></div><div><strong>{published}</strong><span>live products</span></div></div></div></section><section className="zorah-dashboard-panel"><div className="zorah-dashboard-panel-head"><div><span>People</span><h2 className="mt-2 text-2xl">Access mix</h2></div></div><div className="zorah-chart-row"><div className="zorah-donut" style={{background:`conic-gradient(#173d32 0 ${staffRate}%,#d9d0bf ${staffRate}% 100%)`}}><div><strong>{staffRate}%</strong><span>staff</span></div></div><div className="zorah-chart-copy"><div><strong>{staffCount}</strong><span>staff accounts</span></div><div><strong>{customerCount}</strong><span>customers</span></div><div><strong>{roleCounts.super_admin??0}</strong><span>super admin</span></div></div></div></section></div>
  {role==='super_admin'&&<div className="zorah-dashboard-panel mt-4"><div className="zorah-dashboard-panel-head"><div><span>Role distribution</span><h2 className="mt-2 text-2xl">Administration at a glance</h2></div><Link href="/admin/team">Manage roles →</Link></div><div className="zorah-role-bars">{Object.entries(roleCounts).filter(([key])=>key!=='customer').map(([key,count])=><div key={key}><div><span>{key.replaceAll('_',' ')}</span><b>{count}</b></div><i><em style={{width:`${Math.max(5,Math.round(count/Math.max(1,staffCount)*100))}%`}}/></i></div>)}</div></div>}
  <div className="zorah-dashboard-grid"><section className="zorah-dashboard-panel"><div className="zorah-dashboard-panel-head"><div><span>Workspace</span><h2 className="mt-2 text-2xl">Manage Zorah</h2></div></div><div className="zorah-dashboard-modules">{visible.map(([title,description,href])=><Link key={href} href={href} className="zorah-dashboard-module"><div><strong>{title}</strong><p>{description}</p></div><i aria-hidden>↗</i></Link>)}</div></section><aside className="zorah-dashboard-panel"><div className="zorah-dashboard-panel-head"><div><span>Attention</span><h2 className="mt-2 text-2xl">Customer signals</h2></div></div><div className="zorah-dashboard-attention"><Link href="/admin/waitlist"><b>{waitlist.count??0}</b><span>waiting</span><i>→</i></Link><Link href="/admin/enquiries"><b>{enquiries.count??0}</b><span>open enquiries</span><i>→</i></Link><Link href="/admin/enquiries"><b>{customOrders.count??0}</b><span>custom requests</span><i>→</i></Link></div><div className="mt-6 border-t border-black/10 pt-5"><p className="text-xs text-black/55">Your role</p><p className="mt-2 font-serif text-xl">{role.replaceAll('_',' ')}</p><p className="mt-2 text-xs leading-6 text-black/55">Permissions are enforced server-side and by database RLS.</p></div></aside></div></section></main>
}
