'use client'

import { useEffect, useState } from 'react'
type ImageItem={id:string;variant_id:string|null;storage_path:string;alt_text:string;sort_order:number;is_primary:boolean;url:string|null}
type Variant={id:string;sku:string;name:string|null;color_name:string|null}
const input='mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#B08A3C] focus:ring-2 focus:ring-[#B08A3C]/15'
export default function MediaManager({productId,variants}:{productId:string;variants:Variant[]}){
 const [images,setImages]=useState<ImageItem[]>([]),[file,setFile]=useState<File|null>(null),[alt,setAlt]=useState(''),[variantId,setVariantId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{const r=await fetch(`/api/admin/products/${productId}/media`,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok)setImages(d.images??[]);else setError(d.error||'Could not load media.')}; useEffect(()=>{load()},[productId])
 const upload=async()=>{if(!file||busy)return;setError('');setBusy(true);try{const f=new FormData();f.append('file',file);f.append('alt_text',alt);if(variantId)f.append('variant_id',variantId);const r=await fetch(`/api/admin/products/${productId}/media`,{method:'POST',body:f});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Upload failed.');setImages(x=>[...x,d.image]);setFile(null);setAlt('');setVariantId('');const el=document.getElementById('zorah-media-file') as HTMLInputElement|null;if(el)el.value=''}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
 const remove=async(id:string)=>{if(!confirm('Delete this product image?'))return;setBusy(true);try{const r=await fetch(`/api/admin/products/${productId}/media`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_id:id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Delete failed.');setImages(x=>x.filter(i=>i.id!==id))}catch(e){setError(e instanceof Error?e.message:'Delete failed.')}finally{setBusy(false)}}
 return <section className="mt-8 rounded-2xl border border-black/10 bg-white/75 p-5 sm:p-7"><p className="text-[10px] uppercase tracking-[.2em] text-[#5A3524]">2D-3D</p><h2 className="mt-1 font-serif text-2xl">Product media</h2><p className="mt-2 text-sm text-black/55">Private product media is stored in Supabase Storage and previewed with short-lived signed URLs.</p>{error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
 <div className="mt-6 grid gap-4 sm:grid-cols-3"><label className="text-[10px] uppercase tracking-wider">Image<input id="zorah-media-file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>setFile(e.target.files?.[0]??null)} className={input}/></label><label className="text-[10px] uppercase tracking-wider">Alt text<input className={input} maxLength={160} value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Describe the bag image"/></label><label className="text-[10px] uppercase tracking-wider">Variant<select className={input} value={variantId} onChange={e=>setVariantId(e.target.value)}><option value="">Product / all variants</option>{variants.map(v=><option key={v.id} value={v.id}>{v.name||v.color_name||v.sku}</option>)}</select></label></div><button disabled={!file||!alt.trim()||busy} onClick={upload} className="mt-4 rounded-full bg-[#173D32] px-5 py-2.5 text-xs uppercase tracking-wider text-[#F7F3EC] disabled:opacity-40">{busy?'Working…':'Upload image'}</button>
 <div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{images.map(image=><article key={image.id} className="overflow-hidden rounded-xl border border-black/10 bg-white"><div className="aspect-[4/5] bg-[#eee]">{image.url?<img src={image.url} alt={image.alt_text} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-xs text-black/40">Preview unavailable</div>}</div><div className="p-3"><p className="line-clamp-2 text-xs">{image.alt_text}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-black/40">{image.is_primary?'Primary · ':''}{image.variant_id?'Variant image':'Product image'}</p><button disabled={busy} onClick={()=>remove(image.id)} className="mt-3 text-[10px] uppercase tracking-wider text-red-700">Delete image</button></div></article>)}</div>{images.length===0&&<div className="mt-6 rounded-xl border border-dashed border-black/15 px-5 py-10 text-center text-sm text-black/45">No product images yet.</div>}
 </section>
}
