import Link from 'next/link'
import { notFound } from 'next/navigation'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'
import ProductForm from '../product-form'
import VariantManager from './variant-manager'
import MediaManager from './media-manager'
import PublishingPanel from './publishing-panel'
export default async function EditProductPage({params}:{params:Promise<{id:string}>}){await requireRole(['catalog_admin']);const {id}=await params;const supabase=await createClient();const {data,error}=await supabase.from('products').select('id,name,slug,short_description,description,base_price,status,is_featured,badge,seo_title,seo_description,seo_keywords,category_id,published_at,scheduled_publish_at,unpublished_at').eq('id',id).single();if(error||!data)notFound();const {data:variants}=await supabase.from('product_variants').select('id,sku,name,color_name,color_hex,price,stock_quantity,is_available,is_default').eq('product_id',id).order('sort_order').order('created_at');return <main className="zorah-product-editor"><header className="zorah-admin-topbar"><div><Link href="/admin/products" className="brand">ZORAH</Link><div className="links"><Link href="/admin/products" className="pill">Catalogue</Link><Link href="/admin/categories" className="pill">Categories</Link><Link href="/admin" className="pill">Dashboard</Link></div></div></header><section><div className="editor-head"><div><p className="editor-kicker">Catalogue / Product</p><h1 className="editor-title">{data.name}</h1><p className="editor-note">Edit catalogue information, upload product photography, manage variants, control stock and publish this piece.</p></div><div className="editor-actions"><Link href={`/admin/products/${id}/preview`}>Preview store page ↗</Link></div></div><ProductForm initial={{...data,base_price:String(data.base_price),seo_keywords:Array.isArray(data.seo_keywords)?data.seo_keywords.join(', '):'',category_id:data.category_id??''}} /><div className="media-card"><PublishingPanel productId={id} status={data.status} scheduledPublishAt={data.scheduled_publish_at}/></div><div className="media-card"><VariantManager productId={id} initial={(variants??[]) as any}/></div><div className="media-card"><MediaManager productId={id} variants={(variants??[]) as any}/></div></section></main>}
