'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

type Props={productId:string;status:'draft'|'published'|'archived';scheduledPublishAt:string|null}
export default function PublishingPanel({productId,status,scheduledPublishAt}:Props){
 const router=useRouter(); const [nextStatus,setNextStatus]=useState(status); const [schedule,setSchedule]=useState(scheduledPublishAt?new Date(scheduledPublishAt).toISOString().slice(0,16):''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [done,setDone]=useState('')
 async function save(){if(busy)return;setError('');setDone('');setBusy(true);try{const res=await fetch(`/api/admin/products/${productId}/publishing`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:nextStatus,scheduled_publish_at:nextStatus==='draft'&&schedule?new Date(schedule).toISOString():null})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Could not update publishing status.');setDone(nextStatus==='draft'?'Publishing settings saved.':nextStatus==='published'?'Product published.':'Product archived.');router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not update publishing status.')}finally{setBusy(false)}}
 return <section className="mt-8 rounded-2xl border border-[#111111]/10 bg-white/75 p-5 sm:p-7"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#5A3524]">2D-3E</p><h2 className="mt-1 font-serif text-2xl">Publishing</h2><p className="mt-2 text-sm text-black/55">Control catalogue visibility without changing the product content.</p></div><span className="w-fit rounded-full border border-black/10 px-3 py-1 text-[10px] uppercase tracking-wider">Current: {status}</span></div>{error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}{done&&<div role="status" className="mt-5 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{done}</div>}<div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-medium uppercase tracking-[.12em]">Status<select className="mt-2 w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm" value={nextStatus} onChange={e=>setNextStatus(e.target.value as Props['status'])}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="text-xs font-medium uppercase tracking-[.12em]">Schedule publish (optional)<input type="datetime-local" min={new Date().toISOString().slice(0,16)} disabled={nextStatus!=='draft'} value={schedule} onChange={e=>setSchedule(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm disabled:opacity-50"/></label></div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-black/45">Publishing and scheduling are authorized on the server. A browser cannot grant itself catalogue privileges.</p><button disabled={busy} onClick={save} className="rounded-full bg-[#173D32] px-6 py-3 text-xs font-medium uppercase tracking-[.14em] text-[#F7F3EC] disabled:opacity-50">{busy?'Saving…':'Save publishing'}</button></div></section>
}
