import { NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)
const text=(v:unknown,max:number)=>typeof v==='string'?v.trim().slice(0,max):''
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)
export async function GET(){try{await requireRole(['catalog_admin']);const s=await createClient();const {data,error}=await s.from('categories').select('id,name,slug,description,sort_order,is_active').order('sort_order').order('name');if(error)return NextResponse.json({error:'Could not load categories.'},{status:500});return NextResponse.json({categories:data??[]})}catch{return NextResponse.json({error:'Unable to load categories.'},{status:500})}}
export async function POST(request:Request){try{const {user}=await requireRole(['catalog_admin']);const body=await request.json().catch(()=>null);if(!body||typeof body!=='object')return NextResponse.json({error:'Invalid request.'},{status:400});const name=text(body.name,100),slug=slugify(text(body.slug,120)||name);if(name.length<2||!slug)return NextResponse.json({error:'Category name is required.'},{status:400});const s=await createClient();const {data,error}=await s.from('categories').insert({name,slug,description:text(body.description,500)||null,sort_order:Number.isFinite(Number(body.sort_order))?Number(body.sort_order):0,is_active:body.is_active!==false,created_by:user.id,updated_by:user.id}).select('id,name,slug,description,sort_order,is_active').single();if(error)return NextResponse.json({error:error.code==='23505'?'That category already exists.':'Could not create category.'},{status:error.code==='23505'?409:400});return NextResponse.json({category:data},{status:201})}catch{return NextResponse.json({error:'Unable to create category.'},{status:500})}}
export async function PATCH(request:Request){try{const {user}=await requireRole(['catalog_admin']);const body=await request.json().catch(()=>null);if(!uuid(body?.id))return NextResponse.json({error:'Invalid category.'},{status:400});const name=text(body.name,100),slug=slugify(text(body.slug,120)||name);if(name.length<2||!slug)return NextResponse.json({error:'Category name is required.'},{status:400});const s=await createClient();const {data,error}=await s.from('categories').update({name,slug,description:text(body.description,500)||null,sort_order:Number.isFinite(Number(body.sort_order))?Number(body.sort_order):0,is_active:body.is_active!==false,updated_by:user.id}).eq('id',body.id).select('id,name,slug,description,sort_order,is_active').single();if(error)return NextResponse.json({error:error.code==='23505'?'That category already exists.':'Could not update category.'},{status:error.code==='23505'?409:400});return NextResponse.json({category:data})}catch{return NextResponse.json({error:'Unable to update category.'},{status:500})}}
export async function DELETE(request:Request){try{await requireRole(['catalog_admin']);const body=await request.json().catch(()=>null);if(!uuid(body?.id))return NextResponse.json({error:'Invalid category.'},{status:400});const s=await createClient();const {data:used}=await s.from('products').select('id').eq('category_id',body.id).limit(1);if(used?.length)return NextResponse.json({error:'This category is still assigned to a product. Move those products before deleting it.'},{status:409});const {error}=await s.from('categories').delete().eq('id',body.id);if(error)return NextResponse.json({error:'Could not delete category.'},{status:400});return NextResponse.json({ok:true})}catch{return NextResponse.json({error:'Unable to delete category.'},{status:500})}}
