import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { requireRole } from '@/lib/auth/authorization'

const roles=['content_admin','marketing_admin','super_admin'] as const
const slug=/^[a-z0-9]+(?:-[a-z0-9]+)*$/
async function payload(req:Request){const type=req.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('JSON required');const body=await req.json();if(!body||Array.isArray(body)||typeof body!=='object')throw new Error('Invalid payload');return body}
function clean(b:any){if(typeof b.title!=='string'||b.title.trim().length<2||b.title.length>160)throw new Error('Invalid title');if(typeof b.slug!=='string'||!slug.test(b.slug)||b.slug.length>100)throw new Error('Invalid slug');if(typeof b.body!=='string'||b.body.length>50000)throw new Error('Invalid story body');const status=['draft','scheduled','published','archived'].includes(b.status)?b.status:null;if(!status)throw new Error('Invalid status');const tags=Array.isArray(b.tags)?b.tags.filter((x:any)=>typeof x==='string').map((x:string)=>x.trim()).filter(Boolean).slice(0,20):[];return {title:b.title.trim(),slug:b.slug,excerpt:typeof b.excerpt==='string'?b.excerpt.slice(0,500):'',body:b.body,category:typeof b.category==='string'?b.category.slice(0,80):'',tags,status,seo_title:typeof b.seo_title==='string'?b.seo_title.slice(0,160):'',seo_description:typeof b.seo_description==='string'?b.seo_description.slice(0,320):'',scheduled_publish_at:b.scheduled_publish_at||null}}
export async function POST(req:Request){try{const auth=await requireRole([...roles]);const b=clean(await payload(req));const supabase=await createClient();const {data,error}=await supabase.from('journal_articles').insert({...b,created_by:auth.user.id,updated_by:auth.user.id,published_at:b.status==='published'?new Date().toISOString():null}).select('id').single();if(error){if(error.code==='23505')return NextResponse.json({error:'That slug is already in use.'},{status:409});throw error}return NextResponse.json(data,{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to save story'},{status:400})}}
