'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'

type ProductFormValues={id?:string;name:string;slug:string;short_description:string;description:string;base_price:string;status:'draft'|'published'|'archived';is_featured:boolean;badge:string;seo_title:string;seo_description:string;seo_keywords:string;category_id?:string}
type Category={id:string;name:string}
const empty:ProductFormValues={name:'',slug:'',short_description:'',description:'',base_price:'',status:'published',is_featured:false,badge:'',seo_title:'',seo_description:'',seo_keywords:'',category_id:''}
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)
const field='mt-2 w-full rounded-xl border border-[#111111]/12 bg-white px-4 py-3 text-sm outline-none focus:border-[#B08A3C] focus:ring-2 focus:ring-[#B08A3C]/15'
const MAX_FILE_SIZE=10*1024*1024
const MAX_FILES=8
const IMAGE_TYPES=['image/jpeg','image/png','image/webp','image/avif']

export default function ProductForm({initial}:{initial?:ProductFormValues}){
 const router=useRouter();const[form,setForm]=useState<ProductFormValues>(initial??empty);const[categories,setCategories]=useState<Category[]>([]);const[manualSlug,setManualSlug]=useState(!!initial?.slug);const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState(false);const[error,setError]=useState('');const[files,setFiles]=useState<File[]>([])
 useEffect(()=>{if(!manualSlug)setForm(v=>({...v,slug:slugify(v.name)}))},[form.name,manualSlug])
 useEffect(()=>{let cancelled=false;fetch('/api/admin/categories',{cache:'no-store'}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load categories.');return d}).then(d=>{if(!cancelled)setCategories(d.categories??[])}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Could not load categories.')});return()=>{cancelled=true}},[])
 const set=(key:keyof ProductFormValues,value:unknown)=>setForm(v=>({...v,[key]:value}))
 const previews=useMemo(()=>files.map(file=>({name:file.name,url:URL.createObjectURL(file)})),[files])
 useEffect(()=>()=>previews.forEach(item=>URL.revokeObjectURL(item.url)),[previews])
 const chooseFiles=(list:FileList|null)=>{if(!list)return;const selected=Array.from(list);if(selected.length>MAX_FILES){setError(`You can upload up to ${MAX_FILES} product images.`);return}if(selected.some(f=>f.size>MAX_FILE_SIZE)){setError('Each product image must be 10 MiB or smaller.');return}if(selected.some(f=>!IMAGE_TYPES.includes(f.type))){setError('Use JPG, PNG, WebP or AVIF images.');return}setError('');setFiles(selected)}
 async function uploadImages(id:string){if(!files.length)return;setUploading(true);try{for(let index=0;index<files.length;index++){const file=files[index];const body=new FormData();body.append('file',file);body.append('alt_text',`${form.name.trim()} — product image ${index+1}`);const r=await fetch(`/api/admin/products/${id}/media`,{method:'POST',body});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Could not upload ${file.name}.`)}}finally{setUploading(false)}}
 async function deleteCreatedProduct(id:string){try{await fetch(`/api/admin/products/${id}`,{method:'DELETE'})}catch{}}
 async function submit(e:React.FormEvent){e.preventDefault();if(saving||uploading)return;setError('');const name=form.name.trim(),slug=slugify(form.slug),price=Number(form.base_price);if(name.length<2||name.length>160)return setError('Product name must be 2–160 characters.');if(!slug)return setError('Enter a valid product slug.');if(!form.category_id)return setError('Select a product category.');if(!Number.isFinite(price)||price<0||price>1000000000)return setError('Enter a valid NGN price.');if(!form.id&&!files.length)return setError('Add at least one product image.');setSaving(true);try{const requestedStatus=form.status;const payload={...form,name,slug,base_price:price,seo_keywords:form.seo_keywords.split(',').map(x=>x.trim()).filter(Boolean),status:form.id?requestedStatus:'draft'};const res=await fetch(form.id?`/api/admin/products/${form.id}`:'/api/admin/products',{method:form.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Could not save product.');const id=form.id||data.id;if(!id)throw new Error('Product was saved but its ID was not returned.');if(!form.id){try{await uploadImages(id)}catch(uploadError){await deleteCreatedProduct(id);throw uploadError}if(requestedStatus==='published'){const publishRes=await fetch(`/api/admin/products/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,status:'published'})});const publishData=await publishRes.json().catch(()=>({}));if(!publishRes.ok)throw new Error(publishData.error||'Product was created but could not be published. It remains a draft.')}}router.push(`/admin/products/${id}`);router.refresh()}catch(err){setError(err instanceof Error?err.message:'Could not save product.');setSaving(false)}}
 return <form onSubmit={submit} className="space-y-7">{error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
 <section className="rounded-2xl border border-[#111111]/10 bg-white/75 p-5 sm:p-7"><div className="product-form-head"><p>01 · Core catalogue</p><h2 className="mt-1 font-serif text-2xl">Product information</h2><span>Set the product name, category, price and customer-facing story.</span></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2 text-xs font-medium uppercase tracking-[.12em]">Name<input className={field} value={form.name} onChange={e=>set('name',e.target.value)} maxLength={160} required/></label><label className="text-xs font-medium uppercase tracking-[.12em]">Category<select className={field} value={form.category_id??''} onChange={e=>set('category_id',e.target.value)} required><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{!categories.length&&<small className="mt-1 block text-[10px] text-black/45">Create a category first from Admin → Categories.</small>}</label><label className="text-xs font-medium uppercase tracking-[.12em]">Slug<input className={field} value={form.slug} onChange={e=>{setManualSlug(true);set('slug',e.target.value)}} maxLength={120} required/></label><label className="text-xs font-medium uppercase tracking-[.12em]">Price (NGN)<input className={field} type="number" min="0" max="1000000000" step="0.01" inputMode="decimal" value={form.base_price} onChange={e=>set('base_price',e.target.value)} required/></label><label className="sm:col-span-2 text-xs font-medium uppercase tracking-[.12em]">Short description<textarea className={field} rows={3} maxLength={500} value={form.short_description} onChange={e=>set('short_description',e.target.value)}/></label><label className="sm:col-span-2 text-xs font-medium uppercase tracking-[.12em]">Description<textarea className={field} rows={7} maxLength={10000} value={form.description} onChange={e=>set('description',e.target.value)}/></label></div></section>
 {!form.id&&<section className="rounded-2xl border border-[#111111]/10 bg-white/75 p-5 sm:p-7"><div className="product-form-head"><p>02 · Photography</p><h2 className="mt-1 font-serif text-2xl">Product images</h2><span>Upload up to 8 JPG, PNG, WebP or AVIF images. The first becomes the primary storefront image. Uploads are completed before a new product can be published.</span></div><div className="mt-6 grid gap-5"><label className="text-xs font-medium uppercase tracking-[.12em]">Images *<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>chooseFiles(e.target.files)} className={field}/></label>{files.length>0&&<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{previews.map(item=><div key={item.url} className="overflow-hidden rounded-xl border border-[#111111]/10 bg-[#eee9df]"><div className="aspect-[4/5]"><img src={item.url} alt="" className="h-full w-full object-cover"/></div><p className="truncate px-3 py-2 text-[10px] text-black/55">{item.name}</p></div>)}</div>}</div></section>}
 <section className="rounded-2xl border border-[#111111]/10 bg-white/75 p-5 sm:p-7"><div className="product-form-head"><p>{form.id?'02':'03'} · Storefront</p><h2 className="mt-1 font-serif text-2xl">Publishing & merchandising</h2><span>Control visibility, featured placement and customer-facing badges.</span></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-medium uppercase tracking-[.12em]">Status<select className={field} value={form.status} onChange={e=>set('status',e.target.value as ProductFormValues['status'])}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="text-xs font-medium uppercase tracking-[.12em]">Badge<input className={field} maxLength={40} placeholder="New, Bestseller, Limited" value={form.badge} onChange={e=>set('badge',e.target.value)}/></label><label className="sm:col-span-2 flex items-center gap-3 rounded-xl border border-[#111111]/10 p-4 text-sm"><input type="checkbox" checked={form.is_featured} onChange={e=>set('is_featured',e.target.checked)}/> Feature this product in eligible merchandising placements.</label></div></section>
 <section className="rounded-2xl border border-[#111111]/10 bg-white/75 p-5 sm:p-7"><div className="product-form-head"><p>{form.id?'03':'04'} · Discovery</p><h2 className="mt-1 font-serif text-2xl">SEO</h2><span>Optional metadata for search engines and catalogue discovery.</span></div><div className="mt-6 grid gap-5"><label className="text-xs font-medium uppercase tracking-[.12em]">SEO title<input className={field} maxLength={70} value={form.seo_title} onChange={e=>set('seo_title',e.target.value)}/></label><label className="text-xs font-medium uppercase tracking-[.12em]">SEO description<textarea className={field} rows={3} maxLength={170} value={form.seo_description} onChange={e=>set('seo_description',e.target.value)}/></label><label className="text-xs font-medium uppercase tracking-[.12em]">SEO keywords<input className={field} placeholder="leather handbag, Lagos handbag, Zorah" value={form.seo_keywords} onChange={e=>set('seo_keywords',e.target.value)}/></label></div></section>
 <div className="flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-black/45">New products are created as drafts until all images upload successfully.</p><div className="flex flex-col-reverse gap-3 sm:flex-row"><button type="button" onClick={()=>router.push('/admin/products')} className="rounded-full border border-[#111111]/15 px-6 py-3 text-xs font-medium uppercase tracking-[.14em]">Cancel</button><button disabled={saving||uploading} className="rounded-full bg-[#173D32] px-7 py-3 text-xs font-medium uppercase tracking-[.14em] text-[#F7F3EC] disabled:opacity-60">{uploading?'Uploading images…':saving?'Saving…':form.id?'Save changes':form.status==='draft'?'Save draft':'Create & publish product'}</button></div></div>
 </form>
}
