'use client'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'

type Category={id:string;name:string;slug:string}
type ProductFormValues={id?:string;name:string;slug:string;short_description:string;description:string;base_price:string;status:'draft'|'published'|'archived';is_featured:boolean;badge:string;seo_title:string;seo_description:string;seo_keywords:string;category_id:string}
const empty:ProductFormValues={name:'',slug:'',short_description:'',description:'',base_price:'',status:'draft',is_featured:false,badge:'',seo_title:'',seo_description:'',seo_keywords:'',category_id:''}
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)
const field='mt-2 w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm outline-none transition focus:border-[#B08A3C] focus:ring-2 focus:ring-[#B08A3C]/10'

export default function ProductForm({initial}:{initial?:ProductFormValues}){
  const router=useRouter();const [form,setForm]=useState(initial?{...initial,category_id:initial.category_id??''}:empty);const [categories,setCategories]=useState<Category[]>([]);const [manualSlug,setManualSlug]=useState(!!initial?.slug);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [image,setImage]=useState<File|null>(null);const [imageAlt,setImageAlt]=useState('');
  useEffect(()=>{if(!manualSlug)setForm(v=>({...v,slug:slugify(v.name)}))},[form.name,manualSlug]);
  useEffect(()=>{fetch('/api/admin/categories',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>setCategories(d?.categories??[])).catch(()=>{})},[])
  const set=(key:keyof ProductFormValues,value:unknown)=>setForm(v=>({...v,[key]:value}))
  async function submit(e:React.FormEvent){e.preventDefault();if(saving)return;setError('');const name=form.name.trim(),slug=slugify(form.slug),price=Number(form.base_price);if(name.length<2||name.length>160)return setError('Product name must be 2–160 characters.');if(!slug)return setError('Enter a valid product slug.');if(!form.category_id)return setError('Select a product category.');if(!Number.isFinite(price)||price<0||price>1000000000)return setError('Enter a valid NGN price.');if(!form.id&&!image)return setError('Add at least one product image so the storefront has photography.');if(!form.id&&!imageAlt.trim())return setError('Add alt text for the product image.');setSaving(true);try{const res=await fetch(form.id?`/api/admin/products/${form.id}`:'/api/admin/products',{method:form.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,name,slug,base_price:price,category_id:form.category_id,seo_keywords:form.seo_keywords.split(',').map(x=>x.trim()).filter(Boolean)})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Could not save product.');const id=form.id??data.id;if(!form.id&&image&&imageAlt.trim()){const media=new FormData();media.append('file',image);media.append('alt_text',imageAlt.trim());const upload=await fetch(`/api/admin/products/${id}/media`,{method:'POST',body:media});const uploadData=await upload.json().catch(()=>({}));if(!upload.ok)throw new Error(uploadData.error||'Product was created, but its image could not be uploaded. Open the product editor to retry.')}router.push(`/admin/products/${id}`);router.refresh()}catch(err){setError(err instanceof Error?err.message:'Could not save product.');setSaving(false)}}
  return <form onSubmit={submit} className="space-y-6">
    {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
    <section className="product-form-card"><div className="product-form-head"><div><p>01 · Core catalogue</p><h2>Product details</h2><span>Name, category, price and the story customers will read.</span></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2">
      <label className="admin-field">Product name *<input className={field} value={form.name} onChange={e=>set('name',e.target.value)} maxLength={160} placeholder="e.g. Zorah Amina Tote" required/></label>
      <label className="admin-field">Category *<select className={field} value={form.category_id} onChange={e=>set('category_id',e.target.value)} required><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{!categories.length&&<small>No categories yet. Create one in Categories first.</small>}</label>
      <label className="admin-field">Selling price (NGN) *<input className={field} type="number" min="0" max="1000000000" step="0.01" inputMode="decimal" value={form.base_price} onChange={e=>set('base_price',e.target.value)} placeholder="0.00" required/></label>
      <label className="admin-field">URL slug<input className={field} value={form.slug} onChange={e=>{setManualSlug(true);set('slug',e.target.value)}} maxLength={120} required/></label>
      <label className="admin-field sm:col-span-2">Short description<textarea className={field} rows={3} maxLength={500} value={form.short_description} onChange={e=>set('short_description',e.target.value)} placeholder="A concise summary shown in search and product cards."/></label>
      <label className="admin-field sm:col-span-2">Full description<textarea className={field} rows={7} maxLength={10000} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Materials, craftsmanship, dimensions, care and what makes this piece special."/></label>
    </div></section>
    {!form.id&&<section className="product-form-card"><div className="product-form-head"><div><p>02 · Photography</p><h2>Add product image</h2><span>The first image becomes the primary storefront image. JPG, PNG, WebP or AVIF up to 10 MB.</span></div></div><div className="mt-6 grid gap-5 sm:grid-cols-[1fr_1fr]"><label className="admin-field">Product image *<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>setImage(e.target.files?.[0]??null)} className={field}/></label><label className="admin-field">Image alt text *<input className={field} maxLength={160} value={imageAlt} onChange={e=>setImageAlt(e.target.value)} placeholder="Black leather Zorah handbag"/></label></div>{image&&<div className="mt-5 flex items-center gap-4 rounded-xl border border-black/10 bg-[#faf8f3] p-3"><img src={URL.createObjectURL(image)} alt="Selected product" className="h-20 w-20 rounded-lg object-cover"/><div><strong className="text-sm">{image.name}</strong><p className="text-xs text-black/45">Ready to upload · {(image.size/1024/1024).toFixed(2)} MB</p></div></div>}</section>}
    <section className="product-form-card"><div className="product-form-head"><div><p>{form.id?'02':'03'} · Storefront</p><h2>Visibility & merchandising</h2><span>Control publication, badges and featured placement.</span></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="admin-field">Publication status<select className={field} value={form.status} onChange={e=>set('status',e.target.value as ProductFormValues['status'])}><option value="draft">Draft — hidden from customers</option><option value="published">Published — visible in store</option><option value="archived">Archived — retired</option></select></label><label className="admin-field">Badge<input className={field} maxLength={40} placeholder="New, Bestseller, Limited" value={form.badge} onChange={e=>set('badge',e.target.value)}/></label><label className="sm:col-span-2 flex items-center gap-3 rounded-xl border border-black/10 p-4 text-sm"><input type="checkbox" checked={form.is_featured} onChange={e=>set('is_featured',e.target.checked)}/><span><strong>Feature this product</strong><small className="mt-1 block text-xs text-black/45">Makes the product eligible for featured storefront placements.</small></span></label></div></section>
    <section className="product-form-card"><div className="product-form-head"><div><p>{form.id?'03':'04'} · Discovery</p><h2>SEO & search visibility</h2><span>Optional metadata for search engines and catalogue discovery.</span></div></div><div className="mt-6 grid gap-5"><label className="admin-field">SEO title<input className={field} maxLength={70} value={form.seo_title} onChange={e=>set('seo_title',e.target.value)} placeholder="Zorah Amina Tote — Leather Handbag"/></label><label className="admin-field">SEO description<textarea className={field} rows={3} maxLength={170} value={form.seo_description} onChange={e=>set('seo_description',e.target.value)}/></label><label className="admin-field">SEO keywords<input className={field} placeholder="leather handbag, Lagos handbag, Zorah" value={form.seo_keywords} onChange={e=>set('seo_keywords',e.target.value)}/></label></div></section>
    <div className="product-form-actions"><button type="button" onClick={()=>router.push('/admin/products')} className="cancel-button">Cancel</button><button disabled={saving} className="save-product-button">{saving?'Saving…':form.id?'Save changes':'Create product & upload image →'}</button></div>
  </form>
}
