"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { Product } from "@/lib/catalog";
type CartItem={product:Product;quantity:number;variant?:string};
type CommerceContextValue={cart:CartItem[];wishlist:string[];recentlyViewed:string[];cartCount:number;wishlistCount:number;addToBag:(product:Product,quantity?:number,variant?:string)=>void;removeFromBag:(slug:string,variant?:string)=>void;setQuantity:(slug:string,quantity:number,variant?:string)=>void;toggleWishlist:(slug:string)=>void;isWishlisted:(slug:string)=>boolean;trackViewed:(slug:string)=>void};
const CommerceContext=createContext<CommerceContextValue|null>(null);
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}}
export function CommerceProvider({children}:{children:React.ReactNode}){const[cart,setCart]=useState<CartItem[]>([]);const[wishlist,setWishlist]=useState<string[]>([]);const[recentlyViewed,setRecentlyViewed]=useState<string[]>([]);useEffect(()=>{setCart(read("zorah-cart",[]));setWishlist(read("zorah-wishlist",[]));setRecentlyViewed(read("zorah-recently-viewed",[]))},[]);useEffect(()=>{localStorage.setItem("zorah-cart",JSON.stringify(cart))},[cart]);useEffect(()=>{localStorage.setItem("zorah-wishlist",JSON.stringify(wishlist))},[wishlist]);useEffect(()=>{localStorage.setItem("zorah-recently-viewed",JSON.stringify(recentlyViewed))},[recentlyViewed]);
 const addToBag=useCallback((product:Product,quantity=1,variant="Default")=>setCart(current=>{const index=current.findIndex(item=>item.product.slug===product.slug&&item.variant===variant);if(index<0)return[...current,{product,quantity,variant}];return current.map((item,i)=>i===index?{...item,quantity:item.quantity+quantity}:item)}),[]);
 const removeFromBag=useCallback((slug:string,variant="Default")=>setCart(current=>current.filter(item=>!(item.product.slug===slug&&item.variant===variant))),[]);
 const setQuantity=useCallback((slug:string,quantity:number,variant="Default")=>setCart(current=>quantity<=0?current.filter(item=>!(item.product.slug===slug&&item.variant===variant)):current.map(item=>item.product.slug===slug&&item.variant===variant?{...item,quantity}:item)),[]);
 const toggleWishlist=useCallback((slug:string)=>setWishlist(current=>current.includes(slug)?current.filter(item=>item!==slug):[...current,slug]),[]);
 const isWishlisted=useCallback((slug:string)=>wishlist.includes(slug),[wishlist]);
 const trackViewed=useCallback((slug:string)=>setRecentlyViewed(current=>{const next=[slug,...current.filter(item=>item!==slug)].slice(0,8);return next.length===current.length&&next.every((v,i)=>v===current[i])?current:next}),[]);
 const value=useMemo(()=>({cart,wishlist,recentlyViewed,cartCount:cart.reduce((sum,item)=>sum+item.quantity,0),wishlistCount:wishlist.length,addToBag,removeFromBag,setQuantity,toggleWishlist,isWishlisted,trackViewed}),[cart,wishlist,recentlyViewed,addToBag,removeFromBag,setQuantity,toggleWishlist,isWishlisted,trackViewed]);return <CommerceContext.Provider value={value}>{children}</CommerceContext.Provider>}
export function useCommerce(){const context=useContext(CommerceContext);if(!context)throw new Error("useCommerce must be used inside CommerceProvider");return context}
