"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { Product } from "@/lib/catalog";

type CartItem={product:Product;quantity:number;variant:string};
type CommerceContextValue={cart:CartItem[];wishlist:string[];recentlyViewed:string[];cartCount:number;wishlistCount:number;addToBag:(product:Product,quantity?:number,variant?:string)=>void;removeFromBag:(slug:string,variant?:string)=>void;setQuantity:(slug:string,quantity:number,variant?:string)=>void;toggleWishlist:(slug:string)=>void;isWishlisted:(slug:string)=>boolean;trackViewed:(slug:string)=>void};
const CommerceContext=createContext<CommerceContextValue|null>(null);
const STORAGE_VERSION="v2";
const STORAGE_KEYS={cart:`zorah-${STORAGE_VERSION}-cart`,wishlist:`zorah-${STORAGE_VERSION}-wishlist`,recentlyViewed:`zorah-${STORAGE_VERSION}-recently-viewed`} as const;
const MAX_CART_ITEMS=50,MAX_QUANTITY=99,MAX_RECENT=8;
const isSafeSlug=(value:unknown):value is string=>typeof value==="string"&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)&&value.length<=120;
function readStorage<T>(key:string,fallback:T,validate:(value:unknown)=>value is T):T{if(typeof window==="undefined")return fallback;try{const raw=window.localStorage.getItem(key);if(!raw)return fallback;const parsed:unknown=JSON.parse(raw);return validate(parsed)?parsed:fallback}catch{return fallback}}
const isWishlist=(value:unknown):value is string[]=>Array.isArray(value)&&value.length<=200&&value.every(isSafeSlug);
const isCart=(value:unknown):value is CartItem[]=>Array.isArray(value)&&value.length<=MAX_CART_ITEMS&&value.every(item=>{if(!item||typeof item!=="object")return false;const c=item as Partial<CartItem>;return isSafeSlug(c.product?.slug)&&typeof c.product?.name==="string"&&typeof c.product?.priceValue==="number"&&Number.isFinite(c.product.priceValue)&&typeof c.quantity==="number"&&Number.isInteger(c.quantity)&&c.quantity>=1&&c.quantity<=MAX_QUANTITY&&typeof c.variant==="string"&&c.variant.length<=100});
const isRecentlyViewed=(value:unknown):value is string[]=>Array.isArray(value)&&value.length<=MAX_RECENT&&value.every(isSafeSlug);
function writeStorage(key:string,value:unknown){if(typeof window==="undefined")return;try{window.localStorage.setItem(key,JSON.stringify(value))}catch{}}
export function CommerceProvider({children}:{children:React.ReactNode}){const[cart,setCart]=useState<CartItem[]>([]),[wishlist,setWishlist]=useState<string[]>([]),[recentlyViewed,setRecentlyViewed]=useState<string[]>([]),[hydrated,setHydrated]=useState(false);useEffect(()=>{setCart(readStorage(STORAGE_KEYS.cart,[],isCart));setWishlist(readStorage(STORAGE_KEYS.wishlist,[],isWishlist));setRecentlyViewed(readStorage(STORAGE_KEYS.recentlyViewed,[],isRecentlyViewed));setHydrated(true)},[]);useEffect(()=>{if(hydrated)writeStorage(STORAGE_KEYS.cart,cart)},[cart,hydrated]);useEffect(()=>{if(hydrated)writeStorage(STORAGE_KEYS.wishlist,wishlist)},[wishlist,hydrated]);useEffect(()=>{if(hydrated)writeStorage(STORAGE_KEYS.recentlyViewed,recentlyViewed)},[recentlyViewed,hydrated]);
 const addToBag=useCallback((product:Product,quantity=1,variant="Default")=>{if(!isSafeSlug(product.slug))return;const q=Math.min(MAX_QUANTITY,Math.max(1,Math.floor(Number(quantity)||1))),v=String(variant).slice(0,100);setCart(current=>{const index=current.findIndex(item=>item.product.slug===product.slug&&item.variant===v);if(index<0){if(current.length>=MAX_CART_ITEMS)return current;return[...current,{product,quantity:q,variant:v}]}return current.map((item,i)=>i===index?{...item,quantity:Math.min(MAX_QUANTITY,item.quantity+q)}:item)})},[]);
 const removeFromBag=useCallback((slug:string,variant="Default")=>{if(!isSafeSlug(slug))return;setCart(current=>current.filter(item=>!(item.product.slug===slug&&item.variant===variant)))},[]);
 const setQuantity=useCallback((slug:string,quantity:number,variant="Default")=>{if(!isSafeSlug(slug))return;const q=Math.floor(Number(quantity));setCart(current=>{if(!Number.isFinite(q)||q<=0)return current.filter(item=>!(item.product.slug===slug&&item.variant===variant));return current.map(item=>item.product.slug===slug&&item.variant===variant?{...item,quantity:Math.min(MAX_QUANTITY,q)}:item)})},[]);
 const toggleWishlist=useCallback((slug:string)=>{if(!isSafeSlug(slug))return;setWishlist(current=>current.includes(slug)?current.filter(item=>item!==slug):[...current,slug].slice(-200))},[]);
 const isWishlisted=useCallback((slug:string)=>wishlist.includes(slug),[wishlist]);
 const trackViewed=useCallback((slug:string)=>{if(!isSafeSlug(slug))return;setRecentlyViewed(current=>[slug,...current.filter(item=>item!==slug)].slice(0,MAX_RECENT))},[]);
 const value=useMemo(()=>({cart,wishlist,recentlyViewed,cartCount:cart.reduce((sum,item)=>sum+item.quantity,0),wishlistCount:wishlist.length,addToBag,removeFromBag,setQuantity,toggleWishlist,isWishlisted,trackViewed}),[cart,wishlist,recentlyViewed,addToBag,removeFromBag,setQuantity,toggleWishlist,isWishlisted,trackViewed]);return <CommerceContext.Provider value={value}>{children}</CommerceContext.Provider>}
export function useCommerce(){const context=useContext(CommerceContext);if(!context)throw new Error("useCommerce must be used inside CommerceProvider");return context}
