"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useCommerce} from "@/components/commerce-provider";
import type {Product} from "@/lib/catalog";
import {createClient} from "@/lib/supabase/client";

function toneFor(value:string):Product["tone"]{const v=value.toLowerCase();if(v.includes("green"))return"green";if(v.includes("brown")||v.includes("tan"))return"brown";if(v.includes("black"))return"black";return"ivory"}
export function WishlistContent(){
 const{wishlist,toggleWishlist,addToBag}=useCommerce();const[items,setItems]=useState<Product[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{if(!wishlist.length){setItems([]);setLoading(false);return}setLoading(true);try{const s=createClient();const{data}=await s.from("products").select("id,slug,name,base_price,currency,description,category:categories(name),variants:product_variants(color_name,price,is_available,stock_quantity),images:product_images(storage_path,alt_text,is_primary,sort_order)").in("slug",wishlist).eq("status","published");const rows=(data??[]) as any[];const built:Product[]=await Promise.all(rows.map(async p=>{const variants=p.variants??[];const images=p.images??[];const primary=[...images].sort((a:any,b:any)=>Number(b.is_primary)-Number(a.is_primary)||a.sort_order-b.sort_order)[0];const signed=primary?.storage_path?(await s.storage.from("product-media").createSignedUrl(primary.storage_path,900)).data?.signedUrl??null:null;const colors=[...new Set(variants.map((v:any)=>v.color_name).filter(Boolean))] as string[];const price=variants.find((v:any)=>v.price!=null)?.price??Number(p.base_price);const category=Array.isArray(p.category)?p.category[0]?.name??"Handbags":p.category?.name??"Handbags";return{slug:p.slug,name:p.name,price:`${p.currency} ${price.toLocaleString("en-NG")}`,priceValue:price,category,tone:toneFor(colors[0]??category),colors:colors.length?colors:["Zorah"],availability:variants.some((v:any)=>v.is_available&&v.stock_quantity>0)?"In stock":"Made to order",featuredRank:1,description:p.description??"",details:[],variants:colors.length?colors:["Default"],imageUrl:signed}}));if(alive)setItems(built.sort((a,b)=>wishlist.indexOf(a.slug)-wishlist.indexOf(b.slug)))}catch(error){console.error("Wishlist products load failed",error);if(alive)setItems([])}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[wishlist]);
 if(loading)return <div className="jumia-empty-card"><div className="jumia-loading">Loading your saved bags…</div></div>;
 if(!items.length)return <div className="jumia-empty-card"><div className="jumia-empty-icon">♡</div><h2>Your wishlist is empty</h2><p>Save a Zorah bag you love and come back to it anytime.</p><Link className="jumia-primary-btn" href="/shop">Start Shopping</Link></div>;
 return <div className="jumia-product-grid">{items.map(product=><article className="jumia-product-card" key={product.slug}><Link href={`/products/${product.slug}`} className={`jumia-product-image tone-${product.tone}`}>{product.imageUrl?<img src={product.imageUrl} alt={product.name}/>:<span>Z</span>}</Link><button className="jumia-heart" onClick={()=>toggleWishlist(product.slug)} aria-label={`Remove ${product.name} from wishlist`}>♥</button><div className="jumia-product-body"><Link href={`/products/${product.slug}`}><h2>{product.name}</h2></Link><p>{product.category}</p><strong>{product.priceValue?`₦${product.priceValue.toLocaleString("en-NG")}`:"Price on request"}</strong><button className="jumia-card-btn" onClick={()=>addToBag(product)}>Add to Cart</button></div></article>)}</div>;
}
