import { NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const TYPES=new Set(['image/jpeg','image/png','image/webp','image/avif']); const MAX=10*1024*1024
async function validSignature(file:File){const b=new Uint8Array(await file.slice(0,16).arrayBuffer());if(file.type==='image/jpeg')return b[0]===0xff&&b[1]===0xd8&&b[2]===0xff;if(file.type==='image/png')return b.slice(0,8).every((x,i)=>x===[137,80,78,71,13,10,26,10][i]);if(file.type==='image/webp')return String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP';if(file.type==='image/avif')return String.fromCharCode(...b.slice(4,8))==='ftyp';return false}

export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){await requireRole(['catalog_admin']);const {id}=await params;if(!UUID.test(id))return NextResponse.json({error:'Invalid product.'},{status:400});const s=await createClient();const {data,error}=await s.from('product_images').select('id,variant_id,storage_path,alt_text,width,height,sort_order,is_primary,created_at').eq('product_id',id).order('sort_order').order('created_at');if(error)return NextResponse.json({error:'Could not load media.'},{status:400});const rows=await Promise.all((data??[]).map(async image=>{const {data:signed}=await s.storage.from('product-media').createSignedUrl(image.storage_path,900);return {...image,url:signed?.signedUrl??null}}));return NextResponse.json({images:rows})}

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){await requireRole(['catalog_admin']);const {id}=await params;if(!UUID.test(id))return NextResponse.json({error:'Invalid product.'},{status:400});const form=await request.formData().catch(()=>null);const file=form?.get('file');const alt=form?.get('alt_text');const variantId=form?.get('variant_id');if(!(file instanceof File))return NextResponse.json({error:'Image file is required.'},{status:400});if(file.size<1||file.size>MAX)return NextResponse.json({error:'Image must be between 1 byte and 10 MiB.'},{status:400});if(!TYPES.has(file.type)||!(await validSignature(file)))return NextResponse.json({error:'Invalid or unsupported image file.'},{status:400});const altText=typeof alt==='string'?alt.trim().slice(0,160):'';if(!altText)return NextResponse.json({error:'Alt text is required.'},{status:400});if(variantId&&(typeof variantId!=='string'||!UUID.test(variantId)))return NextResponse.json({error:'Invalid variant.'},{status:400});const s=await createClient();const {data:product}=await s.from('products').select('id').eq('id',id).single();if(!product)return NextResponse.json({error:'Product not found.'},{status:404});if(variantId){const {data:v}=await s.from('product_variants').select('id').eq('id',variantId).eq('product_id',id).single();if(!v)return NextResponse.json({error:'Variant not found.'},{status:404})}const ext=file.type==='image/jpeg'?'jpg':file.type.split('/')[1];const path=`products/${id}/${crypto.randomUUID()}.${ext}`;const upload=await s.storage.from('product-media').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(upload.error)return NextResponse.json({error:'Could not upload image.'},{status:400});const {count}=await s.from('product_images').select('id',{count:'exact',head:true}).eq('product_id',id);const {data:image,error}=await s.from('product_images').insert({product_id:id,variant_id:variantId||null,storage_path:path,alt_text:altText,sort_order:count??0,is_primary:(count??0)===0}).select('id,variant_id,storage_path,alt_text,sort_order,is_primary').single();if(error){await s.storage.from('product-media').remove([path]);return NextResponse.json({error:'Could not save image metadata.'},{status:400})}const {data:signed}=await s.storage.from('product-media').createSignedUrl(path,900);return NextResponse.json({image:{...image,url:signed?.signedUrl??null}},{status:201})}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){await requireRole(['catalog_admin']);const {id}=await params;if(!UUID.test(id))return NextResponse.json({error:'Invalid product.'},{status:400});const body=await request.json().catch(()=>null);const imageId=body?.image_id;if(typeof imageId!=='string'||!UUID.test(imageId))return NextResponse.json({error:'Invalid image.'},{status:400});const s=await createClient();const {data:image}=await s.from('product_images').select('id').eq('id',imageId).eq('product_id',id).single();if(!image)return NextResponse.json({error:'Image not found.'},{status:404});if(typeof body.alt_text==='string'){const alt=body.alt_text.trim().slice(0,160);if(!alt)return NextResponse.json({error:'Alt text is required.'},{status:400});const {error}=await s.from('product_images').update({alt_text:alt}).eq('id',imageId).eq('product_id',id);if(error)return NextResponse.json({error:'Could not update image.'},{status:400})}if(body.is_primary===true){await s.from('product_images').update({is_primary:false}).eq('product_id',id).neq('id',imageId);const {error}=await s.from('product_images').update({is_primary:true}).eq('id',imageId).eq('product_id',id);if(error)return NextResponse.json({error:'Could not set primary image.'},{status:400})}return NextResponse.json({ok:true})}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){await requireRole(['catalog_admin']);const {id}=await params;if(!UUID.test(id))return NextResponse.json({error:'Invalid product.'},{status:400});const body=await request.json().catch(()=>null);const imageId=body?.image_id;if(typeof imageId!=='string'||!UUID.test(imageId))return NextResponse.json({error:'Invalid image.'},{status:400});const s=await createClient();const {data:image}=await s.from('product_images').select('storage_path,is_primary').eq('id',imageId).eq('product_id',id).single();if(!image)return NextResponse.json({error:'Image not found.'},{status:404});const {error}=await s.from('product_images').delete().eq('id',imageId).eq('product_id',id);if(error)return NextResponse.json({error:'Could not delete image.'},{status:400});const removed=await s.storage.from('product-media').remove([image.storage_path]);if(removed.error)return NextResponse.json({error:'Image record removed, but storage cleanup needs retry.'},{status:500});return NextResponse.json({ok:true})}
