import Link from 'next/link'
import { requireRole } from '@/lib/auth/authorization'
import { createAdminClient } from '@/lib/supabase/admin'
import { updateAdminRole } from './actions'
import { createStaffAccount } from './create-admin-action'

const roles=[['catalog_admin','Product Admin'],['order_admin','Order Admin'],['content_admin','CMS Admin'],['marketing_admin','Marketing Admin'],['ads_admin','Ads Admin'],['support_admin','Customer Care'],['analytics_admin','Analytics'],['operations_admin','General Operations']] as const
const allRoles=[['customer','Customer'],['super_admin','Super Admin'],...roles] as const
const descriptions:Record<string,string>={super_admin:'Everything: users, roles, catalogue, orders, content, campaigns, ads, support and security.',catalog_admin:'Products, variants, pricing, media, categories, collections and inventory.',order_admin:'Orders, payment state, fulfilment, returns and order-related customer follow-up.',content_admin:'Landing page sections, landing media, Journal and brand storytelling.',marketing_admin:'Campaigns, merchandising, flash sales and promotions.',ads_admin:'Advertising placements and ad campaign operations.',support_admin:'Customer accounts, contact enquiries, custom bags and waitlists.',analytics_admin:'Business reporting and performance visibility.',operations_admin:'Cross-functional operational tools and publishing schedules.',customer:'Normal storefront account only.'}

type Profile={id:string;full_name:string|null;role:string;is_active:boolean;created_at:string}

export default async function AdminTeamPage({searchParams}:{searchParams?:Promise<{error?:string;saved?:string}>}){
  await requireRole(['super_admin'])
  const params=searchParams?await searchParams:{}
  const supabase=createAdminClient()
  const [{data:profiles,error:profileError},{data:userData,error:userError}]=await Promise.all([
    supabase.from('profiles').select('id,full_name,role,is_active,created_at').order('created_at'),
    supabase.auth.admin.listUsers({page:1,perPage:1000}),
  ])
  const emailById=new Map((userData?.users??[]).map(user=>[user.id,user.email??'']))
  const users=((profiles??[]) as Profile[]).map(user=>({...user,email:emailById.get(user.id)??''}))
  const error=profileError||userError
  const messages:Record<string,string>={invalid_create:'Enter a valid email, a password of at least 8 characters, and a staff role.',email_exists:'That email already has an account. Use a new email for a new staff identity.',create_failed:'The staff account could not be created.',profile_failed:'The account was created but could not be assigned its role. It was rolled back safely.',last_admin:'The last active Super Admin cannot be removed.',self_lockout:'You cannot disable or demote your own Super Admin account.',auth_update_failed:'The role was saved, but the authentication record could not be updated.'}

  return <main><header><div><div><Link href="/admin" className="font-serif text-2xl tracking-[.12em]">ZORAH</Link><p className="mt-1 text-[10px] uppercase tracking-[.25em]">Team & permissions</p></div><Link href="/admin" className="text-xs uppercase tracking-[.18em]">Admin overview</Link></div></header><section><p className="zorah-dashboard-kicker">Governance / access</p><h1 className="mt-3 text-5xl">Team access</h1><p className="zorah-dashboard-sub mt-4">Only the Super Admin can create staff identities. Staff accounts are created directly in Supabase Auth with a new login email and password, then assigned one controlled role. Existing customer accounts are never selectable for promotion.</p>

    {params.error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{messages[params.error]||'The requested action could not be completed.'}</div>}
    {params.saved&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Staff account created successfully. Give the staff member the credentials securely; Zorah does not store the password in its database.</div>}

    <div className="zorah-dashboard-panel mt-8"><div className="zorah-dashboard-panel-head"><div><span>Create staff identity</span><h2 className="mt-2 text-2xl">Add a new administrator</h2><p className="mt-2 max-w-2xl text-sm text-black/55">Enter the email and login password you want the new administrator to use. The password is sent only to Supabase Auth over the server and is never written to Zorah tables or audit logs.</p></div></div><form action={createStaffAccount} className="mt-6 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.1em]">Login email<input name="email" type="email" required autoComplete="off" placeholder="cmsadmin@zorah.com" className="normal-case tracking-normal" /></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.1em]">Login password<input name="password" type="password" required minLength={8} autoComplete="new-password" placeholder="At least 8 characters" className="normal-case tracking-normal" /></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.1em]">Staff name<input name="fullName" type="text" maxLength={160} placeholder="Optional display name" className="normal-case tracking-normal" /></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.1em]">Role<select name="role" defaultValue="content_admin" required>{roles.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="md:col-span-2"><button type="submit" className="bg-[#173D32] px-6 py-3 text-[10px] uppercase tracking-[.15em] text-white">Create administrator</button></div></form></div>

    <div className="zorah-dashboard-panel mt-8"><div className="zorah-dashboard-panel-head"><div><span>Role model</span><h2 className="mt-2 text-2xl">One master account, controlled specialists</h2></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roles.map(([r,label])=><div key={r} className="rounded-xl border border-black/10 bg-[#fbfaf7] p-4"><strong className="font-serif text-lg">{label}</strong><p className="mt-1 text-xs text-black/55">{descriptions[r]}</p></div>)}</div></div>

    {error?<div className="zorah-dashboard-panel mt-4 text-sm text-red-900">Unable to load staff accounts.</div>:<div className="mt-4 grid gap-3"><div className="px-1 text-[9px] uppercase tracking-[.14em] text-black/45">Existing staff / access controls</div>{users.filter(user=>user.role!=='customer').map(user=><div key={user.id} className="zorah-dashboard-panel"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><p className="font-serif text-xl">{user.full_name||'Unnamed administrator'}</p><p className="mt-1 truncate text-xs text-black/45">{user.email||'No email available'}</p><p className="mt-2 text-[9px] uppercase tracking-[.14em] text-[#B08A3C]">{user.is_active?'Active':'Disabled'} · {user.role.replaceAll('_',' ')}</p><p className="mt-2 max-w-2xl text-xs leading-6 text-black/55">{descriptions[user.role]||'Controlled staff role.'}</p></div><form action={updateAdminRole} className="grid min-w-[250px] gap-2 sm:grid-cols-[1fr_auto]"><input type="hidden" name="userId" value={user.id}/><select name="role" defaultValue={user.role}>{allRoles.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select name="active" defaultValue={user.is_active?'true':'false'} aria-label="Account status"><option value="true">Active</option><option value="false">Disabled</option></select><button className="bg-[#173D32] px-5 py-2 text-[10px] uppercase tracking-[.13em] text-white sm:col-span-2" type="submit">Save access</button></form></div></div>)}{!users.filter(user=>user.role!=='customer').length&&<div className="zorah-dashboard-panel">No staff accounts found.</div>}</div>}

    <div className="zorah-dashboard-panel mt-5"><span className="zorah-dashboard-kicker">Credential rule</span><h2 className="mt-2 text-2xl">Each administrator gets a unique login.</h2><p className="mt-3 text-sm text-black/60">A person can sign in as staff only with the exact email and password created for that staff identity. Normal customer accounts remain customers. Never share the Super Admin password.</p></div>
  </section></main>
}
