'use client'

import { useEffect, useState } from 'react'

type Branding={media_path:string|null;media_url:string|null;updated_at?:string|null}

type AssetKey='site_logo'|'site_favicon'
const ACCEPT='.png,.jpg,.jpeg,.webp,.svg,.ico,.avif,image/png,image/jpeg,image/webp,image/svg+xml,image/x-icon,image/vnd.microsoft.icon,image/avif'
const MAX=5*1024*1024
const EXT_TYPES:Record<string,string>={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',svg:'image/svg+xml',ico:'image/x-icon',avif:'image/avif'}

export default function BrandingPanel(){
 const[settings,setSettings]=useState<Record<string,Branding>>({}),[files,setFiles]=useState<Record<string,File|null>>({}),[previews,setPreviews]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState<string|null>(null),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/branding',{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to load brand settings.');setSettings(d.settings||{})}catch(e){setError(e instanceof Error?e.message:'Unable to load brand settings.')}finally{setLoading(false)}}
 useEffect(()=>{void load();return()=>Object.values(previews).forEach(url=>url&&URL.revokeObjectURL(url))},[])
 const choose=(key:AssetKey,file:File|null)=>{if(!file)return;const ext=file.name.toLowerCase().split('.').pop()||'';const type=file.type||EXT_TYPES[ext]||'';if(file.size>MAX)return setError('Brand artwork must be 5 MiB or smaller.');if(!EXT_TYPES[ext]&&!type.startsWith('image/'))return setError('Use PNG, JPG, JPEG, WebP, SVG, AVIF or ICO.');const old=previews[key];if(old)URL.revokeObjectURL(old);const next=URL.createObjectURL(file);setFiles(x=>({...x,[key]:file}));setPreviews(x=>({...x,[key]:next}));setError('');setMessage('')}
 const save=async(key:AssetKey)=>{const file=files[key];if(!file||saving)return;setSaving(key);setError('');setMessage('');try{const form=new FormData();form.append('file',file);form.append('kind',key==='site_logo'?'logo':'favicon');const upload=await fetch('/api/admin/branding/media',{method:'POST',body:form}),uploaded=await upload.json().catch(()=>({}));if(!upload.ok)throw new Error(uploaded.error||'Image upload failed.');const response=await fetch('/api/admin/branding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,media_path:uploaded.path})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Could not save brand artwork.');setSettings(x=>({...x,[key]:{media_path:data.media_path,media_url:data.media_url,updated_at:new Date().toISOString()}}));const old=previews[key];if(old)URL.revokeObjectURL(old);setFiles(x=>({...x,[key]:null}));setPreviews(x=>({...x,[key]:''}));setMessage(key==='site_logo'?'Logo updated successfully.':'Favicon updated successfully.')}catch(e){setError(e instanceof Error?e.message:'Could not save brand artwork.')}finally{setSaving(null)}}
 const remove=async(key:AssetKey)=>{if(saving||!confirm(`Remove the current ${key==='site_logo'?'logo':'favicon'}?`))return;setSaving(key);setError('');setMessage('');try{const r=await fetch(`/api/admin/branding?key=${encodeURIComponent(key)}`,{method:'DELETE'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not remove brand artwork.');setSettings(x=>({...x,[key]:{media_path:null,media_url:null,updated_at:new Date().toISOString()}}));setMessage(key==='site_logo'?'Logo removed.':'Favicon removed.')}catch(e){setError(e instanceof Error?e.message:'Could not remove brand artwork.')}finally{setSaving(null)}}
 const card=(key:AssetKey,title:string,description:string,kindLabel:string)=>{const current=settings[key],image=previews[key]||current?.media_url||'';return <article className="zorah-brand-card"><div className="zorah-brand-card-top"><div className="zorah-brand-card-copy"><span>Brand asset</span><h3>{title}</h3><p>{description}</p><small>{current?.media_path?'Active on customer site':'No saved asset yet'}</small></div><div className={`zorah-brand-preview ${key==='site_favicon'?'is-favicon':''}`}>{image?<img src={image} alt={`${title} preview`}/>:<strong>{key==='site_logo'?'Z':'Z'}</strong>}</div></div><div className="zorah-brand-upload"><label className="zorah-brand-file"><span>{files[key]?'Replace selected file':'Choose file'}</span><input type="file" accept={ACCEPT} onChange={e=>choose(key,e.target.files?.[0]||null)}/></label>{files[key]&&<button type="button" onClick={()=>void save(key)} disabled={saving!==null}>{saving===key?`Saving ${kindLabel}…`:`Save ${kindLabel}`}</button>}{current?.media_path&&<button type="button" className="danger" onClick={()=>void remove(key)} disabled={saving!==null}>Remove</button>}</div>{files[key]&&<p className="zorah-brand-selected">Selected: <strong>{files[key]?.name}</strong></p>}</article>}
 return <section className="zorah-branding-panel"><div className="zorah-branding-head"><div><span>Site identity</span><h2>Logo & favicon</h2><p>Change Zorah's logo and browser icon whenever you want. Upload, preview, save, replace or remove without touching code.</p></div><button type="button" onClick={()=>void load()} disabled={loading||saving!==null}>Refresh</button></div>{(error||message)&&<div className={`zorah-cms-alert ${error?'is-error':''}`} role={error?'alert':'status'}>{error||message}</div>}{loading?<div className="zorah-cms-empty">Loading brand assets…</div>:<div className="zorah-brand-grid">{card('site_logo','Website logo','Transparent PNG, WebP or SVG is recommended. JPG and AVIF are also supported.','logo')}{card('site_favicon','Favicon','Use a square PNG, WebP, SVG, AVIF or ICO. A simple Zorah mark works best at small sizes.','favicon')}</div>}</section>
}
