'use client'

import { useEffect, useMemo, useState, type FormEvent } from 'react'

type Section={id:string;section_key:string;section_type:string;eyebrow:string|null;title:string|null;body:string|null;primary_cta_label:string|null;primary_cta_href:string|null;secondary_cta_label:string|null;secondary_cta_href:string|null;media_path:string|null;media_url:string|null;theme:string;is_enabled:boolean;sort_order:number;status:string;scheduled_publish_at:string|null}
type FormState=Omit<Section,'id'|'media_url'> & {media_url?:string}
type Filter='all'|'hero'|'content'|'hidden'|'draft'

const TYPES=['hero','promo','product_rail','editorial','craft','collections','custom_order','journal','testimonial','newsletter','media']
const THEMES=['light','dark','leather','green','ivory']
const STATUSES=['draft','published','archived']
const IMAGE_TYPES='image/jpeg,image/png,image/webp,image/avif,image/svg+xml'
const MAX_IMAGE=10*1024*1024
const empty:FormState={section_key:'',section_type:'hero',eyebrow:'',title:'',body:'',primary_cta_label:'Shop handbags',primary_cta_href:'/shop',secondary_cta_label:'',secondary_cta_href:'',media_path:'',theme:'dark',is_enabled:true,sort_order:10,status:'draft',scheduled_publish_at:null}

export default function LandingCmsPanel(){
 const[sections,setSections]=useState<Section[]>([])
 const[form,setForm]=useState<FormState>(empty)
 const[editingId,setEditingId]=useState<string|null>(null)
 const[file,setFile]=useState<File|null>(null)
 const[preview,setPreview]=useState<string|null>(null)
 const[loading,setLoading]=useState(true)
 const[saving,setSaving]=useState(false)
 const[error,setError]=useState('')
 const[message,setMessage]=useState('')
 const[filter,setFilter]=useState<Filter>('all')

 const heroes=useMemo(()=>sections.filter(s=>s.section_type==='hero'&&s.status!=='archived'),[sections])
 const visibleSections=useMemo(()=>sections.filter(s=>filter==='all'?true:filter==='hero'?s.section_type==='hero':filter==='content'?s.section_type!=='hero'&&s.status!=='archived':filter==='hidden'?!s.is_enabled:filter==='draft'?s.status==='draft':true),[sections,filter])
 const update=(key:keyof FormState,value:unknown)=>setForm(current=>({...current,[key]:value}))
 const clearPreview=()=>{if(preview)URL.revokeObjectURL(preview)}
 const reset=()=>{clearPreview();setEditingId(null);setForm({...empty});setFile(null);setPreview(null);setError('');setMessage('')}
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/content',{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to load landing-page content.');setSections(Array.isArray(d.sections)?d.sections:[])}catch(e){setError(e instanceof Error?e.message:'Unable to load landing-page content.')}finally{setLoading(false)}}
 useEffect(()=>{void load();return()=>clearPreview()},[])
 const edit=(section:Section)=>{clearPreview();setEditingId(section.id);setForm({...section,media_url:section.media_url||'',scheduled_publish_at:section.scheduled_publish_at?new Date(section.scheduled_publish_at).toISOString().slice(0,16):null});setFile(null);setPreview(null);setError('');setMessage('');window.scrollTo({top:0,behavior:'smooth'})}
 const chooseImage=(next:File|null)=>{clearPreview();setFile(null);setPreview(null);if(!next)return;const ext=next.name.toLowerCase().split('.').pop()||'';const allowed=['jpg','jpeg','png','webp','avif','svg'];if(!allowed.includes(ext)&&!IMAGE_TYPES.split(',').includes(next.type))return setError('Use JPG, PNG, WebP, AVIF or SVG for homepage artwork.');if(next.size>MAX_IMAGE)return setError('Each homepage image must be 10 MiB or smaller.');setFile(next);setPreview(URL.createObjectURL(next));setError('');setMessage('')}
 const uploadImage=async()=>{if(!file||saving)return;setSaving(true);setError('');setMessage('');try{const body=new FormData();body.append('file',file);const r=await fetch('/api/admin/content/media',{method:'POST',body}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Artwork upload failed.');update('media_path',d.path||'');update('media_url',d.url||preview||'');clearPreview();setPreview(d.url||null);setFile(null);setMessage('Image uploaded. Save this section to apply it to the homepage.')}catch(e){setError(e instanceof Error?e.message:'Artwork upload failed.')}finally{setSaving(false)}}
 const save=async(event:FormEvent)=>{event.preventDefault();if(saving)return;const key=form.section_key.trim();if(!key)return setError('Give this section a unique key.');if(!editingId&&form.section_type==='hero'&&heroes.length>=5)return setError('Maximum 5 hero slides.');setSaving(true);setError('');setMessage('');try{const payload={section_key:key,section_type:form.section_type,eyebrow:form.eyebrow?.trim()||null,title:form.title?.trim()||null,body:form.body?.trim()||null,primary_cta_label:form.primary_cta_label?.trim()||null,primary_cta_href:form.primary_cta_href||null,secondary_cta_label:form.secondary_cta_label?.trim()||null,secondary_cta_href:form.secondary_cta_href||null,media_path:form.media_path||null,theme:form.theme,is_enabled:form.is_enabled,sort_order:Number(form.sort_order),status:form.status,scheduled_publish_at:form.scheduled_publish_at||null};const r=await fetch(editingId?`/api/admin/content/${editingId}`:'/api/admin/content',{method:editingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not save section.');reset();await load();setMessage('Homepage section saved successfully.')}catch(e){setError(e instanceof Error?e.message:'Could not save section.')}finally{setSaving(false)}}
 const remove=async(id:string)=>{if(!confirm('Remove this homepage section? This cannot be undone.'))return;setSaving(true);setError('');setMessage('');try{const r=await fetch(`/api/admin/content/${id}`,{method:'DELETE'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not remove section.');if(editingId===id)reset();await load();setMessage('Section removed.')}catch(e){setError(e instanceof Error?e.message:'Could not remove section.')}finally{setSaving(false)}}
 const move=async(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=sections.length||saving)return;const a=sections[index],b=sections[target];setSaving(true);setError('');setMessage('');try{const updateOrder=async(s:Section,order:number)=>{const payload={section_key:s.section_key,section_type:s.section_type,eyebrow:s.eyebrow||'',title:s.title||'',body:s.body||'',primary_cta_label:s.primary_cta_label||'',primary_cta_href:s.primary_cta_href||'',secondary_cta_label:s.secondary_cta_label||'',secondary_cta_href:s.secondary_cta_href||'',media_path:s.media_path||'',theme:s.theme,is_enabled:s.is_enabled,sort_order:order,status:s.status,scheduled_publish_at:s.scheduled_publish_at||null};const r=await fetch(`/api/admin/content/${s.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Could not reorder sections.')};await updateOrder(a,b.sort_order);await updateOrder(b,a.sort_order);await load();setMessage('Homepage order updated.')}catch(e){setError(e instanceof Error?e.message:'Could not reorder sections.')}finally{setSaving(false)}}

 return <div className="zorah-cms-editor">
  <div className="zorah-cms-toolbar"><div><strong>Homepage content</strong><span>{sections.length} sections · {heroes.length}/5 hero slides · everything below is editable</span></div><div className="zorah-cms-toolbar-actions"><button type="button" onClick={()=>void load()} disabled={loading||saving}>Refresh</button><a href="/" target="_blank" rel="noreferrer">Preview homepage ↗</a></div></div>
  {(error||message)&&<div className={`zorah-cms-alert ${error?'is-error':''}`} role={error?'alert':'status'}>{error||message}</div>}
  <div className="zorah-cms-grid">
   <form className="zorah-cms-form" onSubmit={save}>
    <div className="zorah-cms-form-head"><div><span>{editingId?'Edit existing content':'Add new content'}</span><h2>{editingId?form.title||form.section_key:'Create homepage section'}</h2></div>{editingId&&<button type="button" onClick={reset}>Cancel</button>}</div>
    <div className="zorah-cms-form-note">Edit the exact content customers see. Changes only reach the customer homepage when the section is enabled and published.</div>
    <label>Section key<input required value={form.section_key} onChange={e=>update('section_key',e.target.value)} placeholder="hero-01, story, site-logo"/></label>
    <div className="zorah-cms-two"><label>Section type<select value={form.section_type} onChange={e=>update('section_type',e.target.value)}>{TYPES.map(type=><option key={type}>{type}</option>)}</select></label><label>Display order<input type="number" min="0" max="10000" value={form.sort_order} onChange={e=>update('sort_order',e.target.value)}/></label></div>
    <label>Small label / eyebrow<input value={form.eyebrow||''} onChange={e=>update('eyebrow',e.target.value)} placeholder="Optional — leave empty for a cleaner design"/></label>
    <label>Headline / title<input value={form.title||''} onChange={e=>update('title',e.target.value)} placeholder="What customers should read"/></label>
    <label>Body copy<textarea rows={6} value={form.body||''} onChange={e=>update('body',e.target.value)} placeholder="The actual copy customers should read."/></label>
    <div className="zorah-cms-group"><h3>Buttons & links</h3><div className="zorah-cms-two"><label>Primary button<input value={form.primary_cta_label||''} onChange={e=>update('primary_cta_label',e.target.value)} placeholder="Shop handbags"/></label><label>Primary link<input value={form.primary_cta_href||''} onChange={e=>update('primary_cta_href',e.target.value)} placeholder="/shop"/></label><label>Secondary button<input value={form.secondary_cta_label||''} onChange={e=>update('secondary_cta_label',e.target.value)} placeholder="Optional"/></label><label>Secondary link<input value={form.secondary_cta_href||''} onChange={e=>update('secondary_cta_href',e.target.value)} placeholder="/our-story"/></label></div></div>
    <div className="zorah-cms-media"><div className="zorah-cms-media-head"><div><h3>Section image</h3><p>Every homepage section can have its own Zorah photograph or artwork. Replace it whenever you want.</p></div>{(form.media_path||preview)&&<button type="button" onClick={()=>{clearPreview();update('media_path','');update('media_url','');setFile(null);setPreview(null)}}>Remove image</button>}</div>{(preview||form.media_url)?<img src={preview||form.media_url||''} alt="Current section artwork preview"/>:<div className="zorah-cms-media-empty"><strong>No image attached</strong><span>Choose an image below to add one.</span></div>}<label className="zorah-cms-file"><span>Choose / replace image</span><input type="file" accept={IMAGE_TYPES} onChange={e=>chooseImage(e.target.files?.[0]||null)}/></label>{file&&<button type="button" onClick={()=>void uploadImage()} disabled={saving}>{saving?'Uploading…':'Upload selected image'}</button>}</div>
    <div className="zorah-cms-two"><label>Theme<select value={form.theme} onChange={e=>update('theme',e.target.value)}>{THEMES.map(theme=><option key={theme}>{theme}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>update('status',e.target.value)}>{STATUSES.map(status=><option key={status}>{status}</option>)}</select></label></div>
    <label>Schedule publish<input type="datetime-local" value={form.scheduled_publish_at||''} onChange={e=>update('scheduled_publish_at',e.target.value||null)}/></label>
    <label className="zorah-cms-check"><input type="checkbox" checked={form.is_enabled} onChange={e=>update('is_enabled',e.target.checked)}/> Visible on customer homepage</label>
    <button className="zorah-cms-save" disabled={saving}>{saving?'Saving…':editingId?'Save changes':'Add section'}</button>
   </form>
   <section className="zorah-cms-list">
    <div className="zorah-cms-list-head"><div><span>Current homepage</span><h2>All sections</h2></div><button type="button" onClick={reset}>+ New section</button></div>
    <div className="zorah-cms-list-help"><strong>{sections.length} saved sections.</strong> These are the records currently in Supabase. Edit any one to change its text, image, buttons, theme, visibility, publishing status or order.</div>
    <div className="zorah-cms-filters">{(['all','hero','content','hidden','draft'] as Filter[]).map(value=><button key={value} type="button" className={filter===value?'is-active':''} onClick={()=>setFilter(value)}>{value==='all'?'All':value==='hero'?'Hero':value==='content'?'Other content':value==='hidden'?'Hidden':'Drafts'} <span>{value==='all'?sections.length:value==='hero'?heroes.length:value==='content'?sections.filter(s=>s.section_type!=='hero'&&s.status!=='archived').length:value==='hidden'?sections.filter(s=>!s.is_enabled).length:sections.filter(s=>s.status==='draft').length}</span></button>)}</div>
    {loading?<div className="zorah-cms-empty">Loading your current homepage…</div>:!visibleSections.length?<div className="zorah-cms-empty"><strong>Nothing in this view</strong><span>Change the filter or add a new homepage section.</span></div>:<div className="zorah-cms-items">{visibleSections.map((section)=>{const index=sections.findIndex(s=>s.id===section.id);return <article className={`zorah-cms-item ${editingId===section.id?'is-editing':''}`} key={section.id}><div className="zorah-cms-thumb">{section.media_url?<img src={section.media_url} alt=""/>:<span>{section.section_type==='hero'?'H':'Z'}</span>}</div><div className="zorah-cms-item-main"><h3>{section.title||section.section_key}</h3><p>{section.section_key} · {section.section_type} · {section.status}{section.is_enabled?'':' · hidden'} · order {section.sort_order}</p>{section.body&&<span>{section.body}</span>}</div><div className="zorah-cms-item-actions"><button type="button" onClick={()=>edit(section)}>Edit</button><button type="button" onClick={()=>void remove(section.id)} disabled={saving}>Remove</button><div className="zorah-cms-order"><button type="button" aria-label="Move section up" onClick={()=>void move(index,-1)} disabled={index===0||saving}>↑</button><button type="button" aria-label="Move section down" onClick={()=>void move(index,1)} disabled={index===sections.length-1||saving}>↓</button></div></div></article>})}</div>}
   </section>
  </div>
 </div>
}
