'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'

export default function CollectionForm({ initial }: { initial?: { id:string; name:string; slug:string; description:string|null; status:string; sort_order:number; seo_title:string|null; seo_description:string|null } }){
 const router=useRouter(); const [form,setForm]=useState(initial??{name:'',slug:'',description:'',status:'draft',sort_order:0,seo_title:'',seo_description:''}); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 const change=(key:string,value:string)=>setForm(f=>({...f,[key]:key==='sort_order'?Number(value):value}))
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const res=await fetch(initial?`/api/admin/collections/${initial.id}`:'/api/admin/collections',{method:initial?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not save collection.');router.push(`/admin/collections/${data.id}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save collection.')}finally{setBusy(false)}}
 return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-black/10 bg-white/75 p-6 sm:p-8">{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<label className="block text-sm">Name<input required maxLength={120} value={form.name} onChange={e=>change('name',e.target.value)} className="mt-2 w-full rounded-xl border border-black/15 bg-white px-4 py-3"/></label><label className="block text-sm">Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={120} value={form.slug} onChange={e=>change('slug',e.target.value)} className="mt-2 w-full rounded-xl border border-black/15 bg-white px-4 py-3"/></label><label className="block text-sm">Description<textarea maxLength={2000} value={form.description??''} onChange={e=>change('description',e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-black/15 bg-white px-4 py-3"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">Status<select value={form.status} onChange={e=>change('status',e.target.value)} className="mt-2 w-full rounded-xl border border-black/15 bg-white px-4 py-3"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="block text-sm">Display order<input type="number" min="0" max="100000" value={form.sort_order} onChange={e=>change('sort_order',e.target.value)} className="mt-2 w-full rounded-xl border border-black/15 bg-white px-4 py-3"/></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">SEO title<input maxLength={70} value={form.seo_title??''} onChange={e=>change('seo_title',e.target.value)} className="mt-2 w-full rounded-xl border border-black/15 bg-white px-4 py-3"/></label><label className="block text-sm">SEO description<input maxLength={170} value={form.seo_description??''} onChange={e=>change('seo_description',e.target.value)} className="mt-2 w-full rounded-xl border border-black/15 bg-white px-4 py-3"/></label></div><button disabled={busy} className="w-full rounded-full bg-[#173D32] px-5 py-3 text-xs font-medium uppercase tracking-[.14em] text-[#F7F3EC] disabled:opacity-50">{busy?'Saving…':'Save collection'}</button></form>
}
