import Link from 'next/link'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'

export default async function AdminCollectionsPage() {
  await requireRole(['catalog_admin'])
  const supabase = await createClient()
  const { data: collections, error } = await supabase.from('collections').select('id,name,slug,status,sort_order,created_at').order('sort_order').order('name')
  return <main className="min-h-screen bg-[#F7F3EC] text-[#111111]"><header className="border-b border-black/10 bg-[#111111] text-[#F7F3EC]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><div><Link href="/admin" className="font-serif text-2xl tracking-[.12em]">ZORAH</Link><p className="mt-1 text-[10px] uppercase tracking-[.25em] text-[#B08A3C]">Collections</p></div><Link href="/admin" className="text-xs uppercase tracking-[.18em] text-white/75">Admin</Link></div></header><section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-[#5A3524]">2D-4</p><h1 className="mt-2 font-serif text-4xl sm:text-5xl">Collections</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-black/65">Group products into curated edits while keeping catalogue permissions enforced by Supabase.</p></div><Link href="/admin/collections/new" className="rounded-full bg-[#173D32] px-5 py-3 text-center text-xs font-medium uppercase tracking-[.14em] text-[#F7F3EC]">New collection</Link></div><div className="mt-8 overflow-hidden rounded-2xl border border-black/10 bg-white/70">{error?<p className="p-6 text-sm text-red-800">Collections could not be loaded.</p>:collections?.length?<div className="divide-y divide-black/10">{collections.map(c=><div key={c.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center"><div><p className="font-serif text-xl">{c.name}</p><p className="text-xs text-black/50">/{c.slug}</p></div><span className="text-xs uppercase tracking-[.12em] text-[#5A3524]">{c.status}</span><span className="text-xs text-black/50">Order {c.sort_order}</span><Link href={`/admin/collections/${c.id}`} className="rounded-full border border-black/15 px-4 py-2 text-center text-xs uppercase tracking-[.12em]">Manage</Link></div>)}</div>:<div className="p-10 text-center"><p className="font-serif text-2xl">No collections yet.</p><p className="mt-2 text-sm text-black/55">Create a curated edit for your catalogue.</p></div>}</div><div className="mt-5"><Link href="/admin/inventory" className="text-xs uppercase tracking-[.16em] text-[#173D32]">Open inventory →</Link></div></section></main>
}
