'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'

type Order={id:string;order_number:string;customer_name:string;email:string;phone:string;address_line1:string;address_line2:string|null;city:string;state:string;country:string;subtotal:number;delivery_fee:number;total:number;currency:string;status:string;payment_status:string;paystack_reference:string|null;created_at:string;updated_at:string;customer_note:string|null;terms_accepted_at:string|null;terms_version:string|null;tracking_number:string|null;carrier:string|null;shipped_at:string|null;delivered_at:string|null;cancelled_at:string|null;admin_note:string|null}
type Item={id:string;product_id:string|null;variant_id:string|null;product_name:string;variant_name:string|null;quantity:number;unit_price:number;line_total:number}
type Event={id:string;status:string;note:string|null;created_at:string}
type Payment={provider:string;reference:string;amount:number;currency:string;status:string;transaction_id:number|null;refunded_amount:number;refund_reference:string|null;refund_status:string|null;paid_at:string|null}
const money=(n:number,currency='NGN')=>currency==='NGN'?`₦${Number(n).toLocaleString('en-NG',{maximumFractionDigits:2})}`:`${currency} ${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`
const title=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export function AdminOrderDetail({orderId}:{orderId:string}){
 const[order,setOrder]=useState<Order|null>(null),[items,setItems]=useState<Item[]>([]),[history,setHistory]=useState<Event[]>([]),[payment,setPayment]=useState<Payment|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[nextStatus,setNextStatus]=useState(''),[note,setNote]=useState(''),[tracking,setTracking]=useState(''),[carrier,setCarrier]=useState(''),[adminNote,setAdminNote]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/admin/orders/${orderId}`,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load order.');setOrder(d.order);setItems(d.items??[]);setHistory(d.history??[]);setPayment(d.payment??null);setTracking(d.order?.tracking_number??'');setCarrier(d.order?.carrier??'');setAdminNote(d.order?.admin_note??'');setNextStatus('')}catch(e){setError(e instanceof Error?e.message:'Could not load order.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[orderId])
 const available=useMemo(()=>{if(!order)return[];const map:Record<string,string[]>={pending:['processing','cancelled'],paid:['processing','cancelled'],processing:['shipped','cancelled'],shipped:['delivered'],delivered:[],cancelled:[],refunded:[]};return map[order.status]??[]},[order])
 const save=async(status?:string)=>{if(!order||saving)return;setSaving(true);setError('');setMessage('');try{const body:Record<string,string>={tracking_number:tracking,carrier,admin_note:adminNote};if(status){body.status=status;body.note=note}const r=await fetch(`/api/admin/orders/${order.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not update order.');setMessage(status?`Order moved to ${title(status)}.`:'Order details saved.');setNote('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not update order.')}finally{setSaving(false)}}
 if(loading)return <section className="admin-order-page"><div className="admin-order-loading">Loading order workspace…</div></section>
 if(!order)return <section className="admin-order-page"><div className="admin-order-error">{error||'Order not found.'}</div></section>
 return <section className="admin-order-page">
  <div className="admin-order-top"><div><Link href="/admin/orders" className="admin-order-back">← Orders</Link><p className="admin-order-kicker">Commerce / Order operations</p><h1>{order.order_number}</h1><p>Placed {new Date(order.created_at).toLocaleString('en-NG')} · {order.customer_name}</p></div><div className="admin-order-top-actions"><span className={`admin-order-status status-${order.status}`}>{title(order.status)}</span><span className={`admin-order-status payment-${order.payment_status}`}>{title(order.payment_status)}</span></div></div>
  {error&&<div className="admin-order-alert error">{error}</div>}{message&&<div className="admin-order-alert success">{message}</div>}
  <div className="admin-order-layout">
   <main className="admin-order-main">
    <section className="admin-order-card"><div className="admin-card-head"><div><span>Fulfilment</span><h2>Order progress</h2></div></div><div className="admin-flow">{['pending','processing','shipped','delivered'].map((state,i)=>{const current=['pending','paid','processing','shipped','delivered'].indexOf(order.status);const active=current>=i;return <div className={`admin-flow-step ${active?'active':''}`} key={state}><b>{i+1}</b><span>{title(state)}</span></div>})}</div><div className="admin-transition"><label>Move order to<select value={nextStatus} onChange={e=>setNextStatus(e.target.value)}><option value="">Choose next status</option>{available.map(s=><option key={s} value={s}>{title(s)}</option>)}</select></label><label>Internal timeline note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note for the order history"/></label><button className="admin-primary-action" disabled={!nextStatus||saving} onClick={()=>void save(nextStatus)}>{saving?'Saving…':'Update status'}</button></div></section>
    <section className="admin-order-card"><div className="admin-card-head"><div><span>Items</span><h2>{items.length} item{items.length===1?'':'s'}</h2></div></div><div className="admin-order-items">{items.map(item=><div className="admin-order-item" key={item.id}><div className="admin-order-thumb">Z</div><div><strong>{item.product_name}</strong><span>{item.variant_name||'Default'} · Qty {item.quantity}</span><small>Unit {money(Number(item.unit_price),order.currency)}</small></div><strong>{money(Number(item.line_total),order.currency)}</strong></div>)}</div><div className="admin-totals"><div><span>Subtotal</span><strong>{money(Number(order.subtotal),order.currency)}</strong></div><div><span>Delivery</span><strong>{money(Number(order.delivery_fee),order.currency)}</strong></div><div className="grand"><span>Total</span><strong>{money(Number(order.total),order.currency)}</strong></div></div></section>
    <section className="admin-order-card"><div className="admin-card-head"><div><span>Timeline</span><h2>Order history</h2></div></div><div className="admin-history">{history.map(event=><div className="admin-history-row" key={event.id}><i/><div><strong>{title(event.status)}</strong><span>{event.note||'Status updated.'}</span><small>{new Date(event.created_at).toLocaleString('en-NG')}</small></div></div>)}</div></section>
   </main>
   <aside className="admin-order-side">
    <section className="admin-order-card"><div className="admin-card-head"><div><span>Customer</span><h2>{order.customer_name}</h2></div></div><div className="admin-contact-lines"><a href={`mailto:${order.email}`}>{order.email}</a><a href={`tel:${order.phone}`}>{order.phone}</a></div></section>
    <section className="admin-order-card"><div className="admin-card-head"><div><span>Delivery</span><h2>Shipping details</h2></div></div><div className="admin-address">{order.address_line1}{order.address_line2&&<><br/>{order.address_line2}</>}<br/>{order.city}, {order.state}<br/>{order.country}</div><div className="admin-fields"><label>Carrier<input value={carrier} onChange={e=>setCarrier(e.target.value)} placeholder="e.g. GIG Logistics"/></label><label>Tracking number<input value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="Tracking reference"/></label><button className="admin-secondary-action" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save delivery details'}</button></div></section>
    <section className="admin-order-card"><div className="admin-card-head"><div><span>Payment</span><h2>{title(order.payment_status)}</h2></div></div>{payment?<div className="admin-payment-details"><div><span>Reference</span><strong>{payment.reference}</strong></div><div><span>Amount</span><strong>{money(Number(payment.amount),payment.currency)}</strong></div><div><span>Provider</span><strong>{title(payment.provider)}</strong></div>{payment.transaction_id&&<div><span>Transaction</span><strong>{payment.transaction_id}</strong></div>}</div>:<p className="admin-muted">No payment record is attached to this order.</p>}</section>
    <section className="admin-order-card"><div className="admin-card-head"><div><span>Internal</span><h2>Staff notes</h2></div></div><textarea className="admin-note-field" value={adminNote} onChange={e=>setAdminNote(e.target.value)} placeholder="Only staff can see this note."/><button className="admin-secondary-action" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save internal note'}</button></section>
    {order.customer_note&&<section className="admin-order-card"><div className="admin-card-head"><div><span>Customer note</span><h2>Checkout message</h2></div></div><p className="admin-muted">{order.customer_note}</p></section>}
   </aside>
  </div>
 </section>
}
