import Link from 'next/link'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'

export default async function AdminAuditPage() {
  await requireRole(['super_admin'])
  const supabase = await createClient()
  const { data: logs, error } = await supabase.from('admin_audit_logs').select('id,actor_id,actor_role,action,resource_type,resource_id,result,before_data,after_data,created_at').order('created_at', { ascending: false }).limit(200)
  return <main className="min-h-screen bg-[#F7F3EC] text-[#111111]"><header className="border-b border-black/10 bg-[#111111] text-[#F7F3EC]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><div><Link href="/admin" className="font-serif text-2xl tracking-[.12em]">ZORAH</Link><p className="mt-1 text-[10px] uppercase tracking-[.25em] text-[#B08A3C]">Audit trail</p></div><Link href="/" className="text-xs uppercase tracking-[.18em] text-white/75">View store</Link></div></header><section className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><p className="text-xs uppercase tracking-[.2em] text-[#5A3524]">2D-10</p><h1 className="mt-2 font-serif text-4xl sm:text-5xl">Administrative audit trail</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-black/65">Security-sensitive catalogue, content, campaign and merchandising changes are recorded by the database trigger. Only Super Admins can read these records.</p>{error && <div className="mt-6 rounded-xl border border-red-900/20 bg-red-50 p-4 text-sm text-red-900">Could not load audit records: {error.message}</div>}<div className="mt-8 overflow-hidden rounded-2xl border border-black/10 bg-white/70"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-black/10 bg-[#111111]/[0.03] text-xs uppercase tracking-[.12em] text-black/50"><tr><th className="px-4 py-4">Time</th><th className="px-4 py-4">Actor / role</th><th className="px-4 py-4">Action</th><th className="px-4 py-4">Resource</th><th className="px-4 py-4">Result</th></tr></thead><tbody>{(logs ?? []).map((log) => <tr key={log.id} className="border-b border-black/5 last:border-0"><td className="whitespace-nowrap px-4 py-4 text-black/60">{new Date(log.created_at).toLocaleString()}</td><td className="px-4 py-4"><div>{log.actor_id ?? 'system'}</div><div className="text-xs text-black/45">{log.actor_role ?? 'system'}</div></td><td className="px-4 py-4 font-semibold">{log.action}</td><td className="px-4 py-4"><div>{log.resource_type}</div><div className="max-w-xs truncate text-xs text-black/45">{log.resource_id ?? 'n/a'}</div></td><td className="px-4 py-4">{log.result}</td></tr>)}</tbody></table></div>{!logs?.length && !error && <p className="p-8 text-sm text-black/55">No administrative changes have been recorded yet.</p>}</div></section></main>
}
