"use client";
import {useEffect,useMemo,useState} from "react";
const empty={section_key:"",section_type:"hero",eyebrow:"",title:"",body:"",primary_cta_label:"Shop handbags",primary_cta_href:"/shop",secondary_cta_label:"",secondary_cta_href:"",media_path:"",theme:"dark",is_enabled:true,sort_order:10,status:"draft",scheduled_publish_at:""};
const types=["hero","promo","product_rail","editorial","craft","collections","custom_order","journal","testimonial","newsletter","media"];
const field="w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm outline-none focus:border-[#B08A3C] focus:ring-2 focus:ring-[#B08A3C]/15";
export default function LandingCms(){
 const[rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[id,setId]=useState<string|null>(null),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const load=async()=>{const r=await fetch("/api/admin/content",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setRows(d.sections??[]);else setMsg(d.error??"Could not load landing content.")};
 useEffect(()=>{load();return()=>{if(preview)URL.revokeObjectURL(preview)}},[]);
 const heroes=useMemo(()=>rows.filter(x=>x.section_type==="hero"&&x.status!=="archived"),[rows]);
 const set=(k:string,v:unknown)=>setForm((x:any)=>({...x,[k]:v}));
 const reset=()=>{setId(null);setForm(empty);setFile(null);if(preview)URL.revokeObjectURL(preview);setPreview(null);setMsg("")};
 const edit=(x:any)=>{setId(x.id);setForm({...empty,...x,scheduled_publish_at:x.scheduled_publish_at?new Date(x.scheduled_publish_at).toISOString().slice(0,16):""});setFile(null);setPreview(null);setMsg("");window.scrollTo({top:0,behavior:"smooth"})};
 const choose=(f:File|null)=>{setFile(f);if(preview)URL.revokeObjectURL(preview);setPreview(f?URL.createObjectURL(f):null)};
 async function uploadArtwork(){if(!file)return;setBusy(true);setMsg("");try{const body=new FormData();body.append("file",file);const r=await fetch("/api/admin/content/media",{method:"POST",body});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Artwork upload failed.");set("media_path",d.path);setMsg("Image uploaded. Save the section to publish the change.");setFile(null)}catch(e){setMsg(e instanceof Error?e.message:"Artwork upload failed.")}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;const key=String(form.section_key||"").trim();if(!key)return setMsg("Give this section a unique key.");if(!id&&form.section_type==="hero"&&heroes.length>=5)return setMsg("You can have up to 5 hero slides.");setBusy(true);setMsg("");try{const payload={...form,section_key:key,sort_order:Number(form.sort_order),scheduled_publish_at:form.scheduled_publish_at||null};const r=await fetch(id?`/api/admin/content/${id}`:"/api/admin/content",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Could not save section.");setMsg("Saved successfully.");reset();await load()}catch(e){setMsg(e instanceof Error?e.message:"Could not save section.")}finally{setBusy(false)}}
 async function removeSection(x:string){if(!confirm("Remove this landing section?"))return;setBusy(true);try{const r=await fetch(`/api/admin/content/${x}`,{method:"DELETE"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Could not remove section.");if(id===x)reset();await load();setMsg("Section removed.")}catch(e){setMsg(e instanceof Error?e.message:"Could not remove section")}finally{setBusy(false)}}
 return <div className="grid gap-6 lg:grid-cols-[minmax(320px,430px)_minmax(0,1fr)]"><form onSubmit={save} className="rounded-2xl border border-black/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><h2 className="font-serif text-3xl">{id?"Edit landing section":"Add landing section"}</h2><p className="mt-1 text-sm text-black/55">Control the customer homepage without touching code.</p></div>{id&&<button type="button" onClick={reset} className="text-xs font-bold underline">Cancel</button>}</div>{msg&&<p className="mt-4 rounded-xl bg-[#173D32]/10 p-3 text-sm text-[#173D32]">{msg}</p>}
 <div className="mt-6 grid gap-4"><label className="grid gap-2 text-xs font-bold">Section key<input required className={field} value={form.section_key} onChange={e=>set("section_key",e.target.value)} placeholder="hero-01, story, site-logo"/></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-2 text-xs font-bold">Section type<select className={field} value={form.section_type} onChange={e=>set("section_type",e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs font-bold">Display order<input className={field} type="number" min="0" max="10000" value={form.sort_order} onChange={e=>set("sort_order",e.target.value)}/></label></div><label className="grid gap-2 text-xs font-bold">Title<input className={field} value={form.title??""} onChange={e=>set("title",e.target.value)} placeholder="Customer-facing headline"/></label><label className="grid gap-2 text-xs font-bold">Body text<textarea className={field} rows={6} value={form.body??""} onChange={e=>set("body",e.target.value)} placeholder="The actual copy customers should read."/></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-2 text-xs font-bold">Primary button<input className={field} value={form.primary_cta_label??""} onChange={e=>set("primary_cta_label",e.target.value)}/></label><label className="grid gap-2 text-xs font-bold">Primary link<input className={field} value={form.primary_cta_href??""} onChange={e=>set("primary_cta_href",e.target.value)}/></label><label className="grid gap-2 text-xs font-bold">Secondary button<input className={field} value={form.secondary_cta_label??""} onChange={e=>set("secondary_cta_label",e.target.value)}/></label><label className="grid gap-2 text-xs font-bold">Secondary link<input className={field} value={form.secondary_cta_href??""} onChange={e=>set("secondary_cta_href",e.target.value)}/></label></div>
 <div className="rounded-xl border border-black/10 p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Section image</h3><p className="mt-1 text-xs text-black/50">Upload a new image or leave this section text-only.</p></div>{form.media_path&&<button type="button" className="text-xs font-bold text-red-700 underline" onClick={()=>set("media_path","")}>Remove image</button>}</div>{(preview||form.media_path)&&<div className="mt-4 aspect-[16/8] overflow-hidden rounded-lg bg-[#e8e2d8]">{preview?<img src={preview} alt="New artwork preview" className="h-full w-full object-cover"/>:form.media_path?<img src={form.media_path} alt="Current section artwork" className="h-full w-full object-cover"/>:null}</div>}<input className={`${field} mt-4`} type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>choose(e.target.files?.[0]??null)}/>{file&&<button type="button" disabled={busy} onClick={uploadArtwork} className="mt-3 rounded-full border border-[#173D32] px-4 py-2 text-xs font-bold text-[#173D32]">Upload image</button>}</div>
 <div className="grid grid-cols-2 gap-3"><label className="grid gap-2 text-xs font-bold">Theme<select className={field} value={form.theme} onChange={e=>set("theme",e.target.value)}>{["light","dark","leather","green","ivory"].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs font-bold">Status<select className={field} value={form.status} onChange={e=>set("status",e.target.value)}>{["draft","published","archived"].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={!!form.is_enabled} onChange={e=>set("is_enabled",e.target.checked)}/> Show this section</label><button disabled={busy} className="w-full rounded-full bg-[#173D32] px-5 py-3 text-xs font-bold uppercase tracking-[.12em] text-white disabled:opacity-50">{busy?"Saving…":id?"Save section":"Add section"}</button></div></form>
 <section className="rounded-2xl border border-black/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-end justify-between gap-4"><div><h2 className="font-serif text-3xl">Homepage controls</h2><p className="mt-1 text-sm text-black/55">{heroes.length}/5 hero slides. Edit, reorder, hide or remove any section.</p></div><button type="button" onClick={load} className="text-xs font-bold underline">Refresh</button></div><div className="mt-5 rounded-xl bg-[#F5F1E9] p-4 text-sm"><strong>Logo:</strong> create or edit the <strong>site-logo</strong> section and use its image upload. The customer header uses that image automatically.</div><div className="mt-6 grid gap-3">{rows.map(x=><article key={x.id} className="rounded-xl border border-black/10 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><h3 className="font-serif text-2xl">{x.title||x.section_key}</h3><p className="mt-1 text-xs text-black/50">{x.section_type} · {x.status} · order {x.sort_order}{x.is_enabled?" · visible":" · hidden"}</p></div><div className="flex shrink-0 gap-2"><button type="button" onClick={()=>edit(x)} className="rounded-full border border-black/15 px-4 py-2 text-xs font-bold">Edit</button><button type="button" onClick={()=>removeSection(x.id)} disabled={busy} className="rounded-full border border-red-200 px-4 py-2 text-xs font-bold text-red-700">Remove</button></div></div></article>)}</div></section></div>
}
