"use client";
import {useEffect,useLayoutEffect,useMemo,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import {useCommerce} from "@/components/commerce-provider";
gsap.registerPlugin(ScrollTrigger);

type CmsSection={id?:string;section_key:string;section_type:string;eyebrow?:string|null;title?:string|null;body?:string|null;primary_cta_label?:string|null;primary_cta_href?:string|null;secondary_cta_label?:string|null;secondary_cta_href?:string|null;media_path?:string|null;media_url?:string|null;theme?:string|null;is_enabled?:boolean;sort_order?:number};
type HeroSlide={key:string;title:string;tone:"green"|"tan"|"ink";body:string;primaryLabel:string;primaryHref:string;secondaryLabel:string;secondaryHref:string;media?:string};
const fallbackHero:HeroSlide[]=[
 {key:"hero-01",title:"Carry your point of view.",tone:"green",body:"Leather handbags made in Lagos, designed for the life you actually live.",primaryLabel:"Shop handbags",primaryHref:"/shop",secondaryLabel:"Explore",secondaryHref:"#collections"},
 {key:"hero-02",title:"Beautiful bags, made with intention.",tone:"tan",body:"Thoughtful shapes, considered materials and a finish made to be carried often.",primaryLabel:"Shop the edit",primaryHref:"/shop",secondaryLabel:"Our story",secondaryHref:"/our-story"},
 {key:"hero-03",title:"Made in Lagos. Made to last.",tone:"ink",body:"A strong everyday bag should look good, work hard and last.",primaryLabel:"View collection",primaryHref:"/shop",secondaryLabel:"The craft",secondaryHref:"#craft"},
];
const fallbackCollections=[
 {key:"wear-01",title:"The everyday edit",body:"Work, weekends and everything between.",theme:"green"},
 {key:"wear-02",title:"After dark",body:"Strong silhouettes for day into evening.",theme:"dark"},
 {key:"wear-03",title:"Weekend in colour",body:"A little more colour, the same considered construction.",theme:"leather"},
 {key:"wear-04",title:"The signature",body:"Quiet confidence, shaped in leather and finished by hand.",theme:"ivory"},
];
function toneFor(value?:string|null):HeroSlide["tone"]{const v=(value??"").toLowerCase();if(v==="leather"||v==="brown"||v==="tan")return"tan";if(v==="dark"||v==="black")return"ink";return"green"}
function CmsMedia({src,alt,className}:{src?:string|null;alt:string;className?:string}){return src?<img src={src} alt={alt} className={className??""}/>:null}
function cleanHref(value?:string|null,fallback="/shop"){return value&&value.startsWith("/")?value:fallback}
function ordered<T extends CmsSection>(items:T[]){return[...items].sort((a,b)=>(a.sort_order??0)-(b.sort_order??0))}

export function EditorialMotion({sections=[],logoUrl}:{sections?:CmsSection[];logoUrl?:string|null}){
 const{cartCount}=useCommerce();
 const enabled=useMemo(()=>sections.filter(s=>s.is_enabled!==false),[sections]);
 const byKey=useMemo(()=>new Map(enabled.map(s=>[s.section_key,s])),[enabled]);
 const heroSlides=useMemo<HeroSlide[]>(()=>{
  const cms=ordered(enabled.filter(s=>s.section_type==="hero"&&s.section_key!=="site-logo")).slice(0,5);
  const source=cms.length?cms:fallbackHero.map(x=>({...x,section_type:"hero"} as unknown as CmsSection));
  return source.map((s,index)=>{const f=fallbackHero[index%fallbackHero.length];return{key:s.section_key,title:s.title?.trim()||f.title,tone:toneFor(s.theme),body:s.body?.trim()||f.body,primaryLabel:s.primary_cta_label?.trim()||f.primaryLabel,primaryHref:cleanHref(s.primary_cta_href,f.primaryHref),secondaryLabel:s.secondary_cta_label?.trim()||f.secondaryLabel,secondaryHref:cleanHref(s.secondary_cta_href,f.secondaryHref),media:s.media_url||s.media_path||f.media}});
 },[enabled]);
 const collections=useMemo(()=>{const cms=ordered(enabled.filter(s=>s.section_key.startsWith("wear-")||s.section_type==="collections")).slice(0,8);return cms.length?cms:fallbackCollections},[enabled]);
 const[active,setActive]=useState(0);
 useEffect(()=>{setActive(value=>Math.min(value,Math.max(0,heroSlides.length-1)));const timer=window.setInterval(()=>setActive(value=>(value+1)%heroSlides.length),5000);return()=>window.clearInterval(timer)},[heroSlides.length]);
 useLayoutEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const ctx=gsap.context(()=>{gsap.fromTo(".zorah-reveal",{y:20,opacity:0},{y:0,opacity:1,duration:.65,stagger:.05,ease:"power3.out"});gsap.utils.toArray<HTMLElement>(".zorah-scroll-reveal").forEach(el=>gsap.fromTo(el,{y:26,opacity:0},{y:0,opacity:1,duration:.7,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 90%",once:true}}));gsap.utils.toArray<HTMLElement>(".zorah-image-drift").forEach(el=>gsap.to(el,{yPercent:-4,ease:"none",scrollTrigger:{trigger:el,start:"top bottom",end:"bottom top",scrub:1.4}}))});return()=>ctx.revert()},[]);
 const activeHero=heroSlides[active]??heroSlides[0];
 const craft=byKey.get("craft-story")||byKey.get("craft");
 const editorial=byKey.get("editorial");
 const editorialA=byKey.get("editorial-a");
 const editorialB=byKey.get("editorial-b");
 const journalA=byKey.get("journal-01");
 const journalB=byKey.get("journal-02");
 const cta=byKey.get("cta")||byKey.get("custom-order");
 const extra=enabled.filter(s=>!new Set(["site-logo","hero","collections","product_rail","craft","editorial","journal","custom_order"]).has(s.section_type)&&!s.section_key.startsWith("wear-")&&!s.section_key.startsWith("editorial-")&&!s.section_key.startsWith("journal-")&&s.section_key!=="cta");
 return <div className="zorah-site">
  <header className="zorah-header"><div className="zorah-header-inner"><nav className="zorah-nav"><a href="/shop">Shop</a><a href="#collections">Collections</a><a href="#craft">Craft</a></nav><a href="/" className="zorah-logo" aria-label="Zorah Handbags"><img src={logoUrl||"/brand/zorah-logo.webp"} alt="Zorah Handbags"/></a><nav className="zorah-nav zorah-nav-right"><a href="/account">Account</a><a className="zorah-shop-link" href="/cart" aria-label={`Open shopping bag${cartCount?` (${cartCount} items)`:""}`}>Bag{cartCount>0?` (${cartCount})`:""} <span>→</span></a></nav></div></header>
  <main>
   <section className="zorah-hero" aria-labelledby="zorah-title"><div className="zorah-hero-image" aria-hidden="true">{heroSlides.map((slide,index)=><div key={slide.key} className={`hero-slide hero-slide-${slide.tone} ${index===active?"is-active":""}`}>{slide.media&&<CmsMedia src={slide.media} alt="" className="hero-cms-image"/>}</div>)}</div><div className="zorah-hero-overlay"/><div className="zorah-hero-inner"><div className="zorah-hero-copy"><h1 id="zorah-title" className="zorah-display zorah-reveal">{activeHero.title}</h1><p className="zorah-lede zorah-reveal">{activeHero.body}</p><div className="zorah-actions zorah-reveal"><a className="zorah-btn zorah-btn-dark" href={activeHero.primaryHref}>{activeHero.primaryLabel}<span>→</span></a>{activeHero.secondaryLabel&&<a className="zorah-link" href={activeHero.secondaryHref}>{activeHero.secondaryLabel}</a>}</div></div><div className="hero-slide-controls zorah-reveal"><div className="hero-slide-count"><strong>0{active+1}</strong><span>/ 0{heroSlides.length}</span></div><div className="hero-dots">{heroSlides.map((slide,index)=><button type="button" key={slide.key} className={index===active?"is-active":""} onClick={()=>setActive(index)} aria-label={`Show slide ${index+1}`}><span/></button>)}</div></div></div></section>
   <section id="collections" className="zorah-collection-strip"><div className="collection-head"><h2 className="zorah-display zorah-scroll-reveal">The pieces<br/><em>people notice.</em></h2><a className="zorah-underlink zorah-scroll-reveal" href="/shop">Shop all bags <span>→</span></a></div><div className="collection-rail" role="list">{collections.map((item:any,index:number)=>{const cms=Boolean(item.section_key);const title=cms?(item.title||`Collection ${index+1}`):item.title;const media=cms?(item.media_url||item.media_path):undefined;return <a className="collection-card zorah-scroll-reveal" href={cms?cleanHref(item.primary_cta_href):"/shop"} role="listitem" key={cms?item.section_key:item.key}><div className={`collection-image collection-image-${toneFor(item.theme)}`}>{media&&<CmsMedia src={media} alt={title} className="cms-fill-image"/>}</div><div className="collection-card-copy"><strong>{title}</strong><span>{cms?(item.body||"Explore the collection"):item.body}</span></div></a>})}</div></section>
   <section className="zorah-wear-section"><div className="zorah-wear-intro"><h2 className="zorah-display zorah-scroll-reveal">Worn<br/><em>your way.</em></h2><a className="zorah-underlink zorah-scroll-reveal" href="/shop">Continue to the collection <span>↗</span></a></div><div className="wear-rail" role="list">{collections.slice(0,4).map((item:any,index:number)=><article className="wear-card zorah-scroll-reveal" role="listitem" key={`wear-${item.section_key||item.key}`}><div className={`wear-image wear-image-${toneFor(item.theme)}`}>{(item.media_url||item.media_path)&&<CmsMedia src={item.media_url||item.media_path} alt={item.title||"Zorah handbag"} className="cms-fill-image"/>}</div><div className="wear-copy"><strong>{item.title||"Zorah handbag"}</strong><span>Explore the piece</span></div></article>)}</div></section>
   <section id="craft" className="zorah-story-grid"><div className="story-image zorah-image-drift">{(craft?.media_url||craft?.media_path)&&<CmsMedia src={craft.media_url||craft.media_path} alt="Zorah craftsmanship in Lagos" className="story-cms-image"/>}</div><div className="story-copy"><h2 className="zorah-display zorah-scroll-reveal">{craft?.title||"Made in Lagos. Made to last."}</h2><p className="zorah-body zorah-scroll-reveal">{craft?.body||"Cut, assembled and finished with an eye for the details you feel before you notice them."}</p>{craft?.primary_cta_label&&<a className="zorah-underlink zorah-scroll-reveal" href={cleanHref(craft.primary_cta_href,"/our-story")}>{craft.primary_cta_label}<span>→</span></a>}</div></section>
   <section className="zorah-editorial-band"><div className="editorial-copy"><h2 className="zorah-display zorah-scroll-reveal">{editorial?.title||"One bag. Many lives."}</h2>{editorial?.body&&<p className="zorah-body zorah-scroll-reveal">{editorial.body}</p>}</div>{[editorialA,editorialB].map((item,index)=><div key={item?.section_key||index} className={`editorial-photo editorial-photo-${index===0?"a":"b"} zorah-image-drift`}>{item?.media_url||item?.media_path?<CmsMedia src={item.media_url||item.media_path} alt={item.title||"Zorah handbag editorial"} className="cms-fill-image"/>:null}</div>)}</section>
   <section id="journal" className="zorah-journal"><div className="journal-grid">{[journalA,journalB].filter(Boolean).map((item:any,index:number)=><a className="journal-feature zorah-scroll-reveal" href={cleanHref(item.primary_cta_href,"/journal")} key={item.section_key}><div className={`journal-image journal-image-${index===0?"green":"tan"}`}>{item.media_url||item.media_path?<CmsMedia src={item.media_url||item.media_path} alt={item.title||"Zorah journal"} className="cms-fill-image"/>:null}</div><div><h3>{item.title||"The Zorah journal."}</h3><p className="zorah-body">{item.body||"Stories from the house."}</p></div></a>)}</div></section>
   {extra.map(section=><section key={section.id||section.section_key} className={`zorah-cms-extra zorah-cms-extra-${toneFor(section.theme)}`}><div className="zorah-cms-extra-inner"><div>{section.media_url||section.media_path?<CmsMedia src={section.media_url||section.media_path} alt={section.title||"Zorah"} className="cms-fill-image"/>:null}</div><div className="zorah-cms-extra-copy"><h2 className="zorah-display">{section.title||"Zorah"}</h2>{section.body&&<p className="zorah-body">{section.body}</p>}<div className="zorah-actions">{section.primary_cta_label&&<a className="zorah-btn zorah-btn-light" href={cleanHref(section.primary_cta_href)}>{section.primary_cta_label}<span>→</span></a>}{section.secondary_cta_label&&<a className="zorah-link" href={cleanHref(section.secondary_cta_href)}>{section.secondary_cta_label}</a>}</div></div></div></section>)}
   <section className="zorah-cta-section"><h2 className="zorah-display zorah-scroll-reveal">{cta?.title||"Find the one that feels like you."}</h2>{cta?.body&&<p className="zorah-body zorah-scroll-reveal">{cta.body}</p>}<div className="zorah-actions zorah-scroll-reveal"><a className="zorah-btn zorah-btn-light" href={cleanHref(cta?.primary_cta_href,"/shop")}>{cta?.primary_cta_label||"Shop handbags"}<span>→</span></a></div></section>
  </main>
  <footer className="zorah-footer"><img src={logoUrl||"/brand/zorah-logo.webp"} alt="Zorah Handbags"/><div><span>Lagos · Nigeria</span><a href="/account">Account</a><a href="/our-story">Our story</a><a href="/journal">Journal</a><a href="/cart">Bag</a></div><small>© {new Date().getFullYear()} Zorah Handbags</small></footer>
 </div>;
}
