'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'

export default function JournalForm({ mode, article, userId }: { mode: 'create'|'edit'; article?: Record<string, any>; userId: string }) {
  const router = useRouter(); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  const [form,setForm]=useState({title:article?.title??'',slug:article?.slug??'',excerpt:article?.excerpt??'',body:article?.body??'',category:article?.category??'',tags:(article?.tags??[]).join(', '),status:article?.status??'draft',seo_title:article?.seo_title??'',seo_description:article?.seo_description??'',scheduled_publish_at:article?.scheduled_publish_at?new Date(article.scheduled_publish_at).toISOString().slice(0,16):''})
  const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}))
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const res=await fetch(mode==='create'?'/api/admin/journal':'/api/admin/journal/'+article?.id,{method:mode==='create'?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),userId})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not save story');router.push('/admin/journal')}catch(err){setError(err instanceof Error?err.message:'Could not save story')}finally{setSaving(false)}}
  return <form onSubmit={submit} className="mt-8 space-y-6 rounded-2xl border border-black/10 bg-white p-5 sm:p-8"><div className="grid gap-6 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Title</span><input required maxLength={160} value={form.title} onChange={e=>set('title',e.target.value)} className="field" /></label><label><span className="field-label">Slug</span><input required maxLength={100} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={e=>set('slug',e.target.value.toLowerCase())} className="field" /></label><label><span className="field-label">Category</span><input maxLength={80} value={form.category} onChange={e=>set('category',e.target.value)} className="field" /></label><label className="sm:col-span-2"><span className="field-label">Excerpt</span><textarea maxLength={500} value={form.excerpt} onChange={e=>set('excerpt',e.target.value)} className="field min-h-24" /></label><label className="sm:col-span-2"><span className="field-label">Story body</span><textarea required maxLength={50000} value={form.body} onChange={e=>set('body',e.target.value)} className="field min-h-80" /></label><label className="sm:col-span-2"><span className="field-label">Tags · comma separated</span><input maxLength={500} value={form.tags} onChange={e=>set('tags',e.target.value)} className="field" /></label><label><span className="field-label">Status</span><select value={form.status} onChange={e=>set('status',e.target.value)} className="field"><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label><span className="field-label">Scheduled publish</span><input type="datetime-local" value={form.scheduled_publish_at} onChange={e=>set('scheduled_publish_at',e.target.value)} className="field" /></label><label className="sm:col-span-2"><span className="field-label">SEO title</span><input maxLength={160} value={form.seo_title} onChange={e=>set('seo_title',e.target.value)} className="field" /></label><label className="sm:col-span-2"><span className="field-label">SEO description</span><textarea maxLength={320} value={form.seo_description} onChange={e=>set('seo_description',e.target.value)} className="field min-h-24" /></label></div>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button disabled={saving} className="rounded-full bg-[#111111] px-6 py-3 text-xs uppercase tracking-[.15em] text-white disabled:opacity-50">{saving?'Saving…':'Save story'}</button></form>
}
