import Link from 'next/link'
import { requireRole } from '@/lib/auth/authorization'
import { createClient } from '@/lib/supabase/server'

export default async function AdminJournalPage() {
  await requireRole(['content_admin', 'marketing_admin', 'super_admin'])
  const supabase = await createClient()
  const { data: articles } = await supabase.from('journal_articles').select('id,title,slug,status,category,published_at,scheduled_publish_at,updated_at').order('updated_at', { ascending: false }).limit(50)
  return <main className="min-h-screen bg-[#F7F3EC] text-[#111111]"><header className="border-b border-black/10 bg-[#111111] text-[#F7F3EC]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><div><Link href="/admin" className="font-serif text-2xl tracking-[.12em]">ZORAH</Link><p className="mt-1 text-[10px] uppercase tracking-[.25em] text-[#B08A3C]">Journal studio</p></div><Link href="/journal" className="text-xs uppercase tracking-[.18em] text-white/75">View journal</Link></div></header><section className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs uppercase tracking-[.2em] text-[#5A3524]">2D-7</p><h1 className="mt-2 font-serif text-4xl sm:text-5xl">Journal</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-black/65">Create editorial stories about leather, Lagos, design and the Zorah house. Content is controlled separately from the website code.</p></div><Link href="/admin/journal/new" className="rounded-full bg-[#111111] px-5 py-3 text-xs font-medium uppercase tracking-[.15em] text-white">New story</Link></div><div className="mt-8 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="divide-y divide-black/10">{(articles ?? []).map(a => <Link key={a.id} href={`/admin/journal/${a.id}`} className="grid gap-2 px-5 py-5 transition hover:bg-black/[.025] sm:grid-cols-[1fr_auto] sm:items-center"><div><h2 className="font-serif text-2xl">{a.title}</h2><p className="mt-1 text-xs uppercase tracking-[.12em] text-black/45">{a.category || 'Uncategorised'} · {a.status}</p></div><span className="text-xs uppercase tracking-[.15em] text-[#5A3524]">Edit →</span></Link>)}{!(articles?.length) && <div className="px-5 py-12 text-sm text-black/55">No stories yet. Create the first editorial piece.</div>}</div></div></section></main>
}
