'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'

export default function InventoryAdjuster({variantId}:{variantId:string}){
 const router=useRouter();const [delta,setDelta]=useState(1);const [reason,setReason]=useState('restock');const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('')
 async function submit(){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/inventory/movement',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({variant_id:variantId,quantity_delta:delta,reason,notes})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not update inventory.');setMessage('Inventory updated.');setNotes('');router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'Could not update inventory.')}finally{setBusy(false)}}
 return <div className="zorah-inventory-adjuster"><div className="zorah-inventory-adjust-fields"><label>Quantity<input type="number" min="-100000" max="100000" value={delta} onChange={e=>setDelta(Number(e.target.value))}/><small>Use + to add stock, − to remove it.</small></label><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option value="restock">Restock</option><option value="sale">Sale</option><option value="adjustment">Adjustment</option><option value="return">Return</option><option value="damage">Damage</option><option value="correction">Correction</option></select></label><label className="zorah-inventory-notes">Notes<input maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional audit note"/></label><button disabled={busy||delta===0||!Number.isInteger(delta)} onClick={submit}>{busy?'Saving…':'Adjust stock'}</button></div>{message&&<p className="zorah-inventory-adjust-message" role="status">{message}</p>}</div>
}
